[project]
name = "POTATO"
description = "Backend server for BW's needs"
version = "1.0.0"
requires-python = "==3.12.*"
dependencies = [
    "SQLAlchemy",
    "web.py",
    "wsgilog",
    "alembic",
]
authors = [
    {name="Bailey Danyluk"}
]
maintainers = [
    {name="Bailey Danyluk"}
]