import re
import logging
import shutil
from uuid import UUID, uuid5
from pathlib import Path

from bw.state import State
from bw.response import JsonResponse, WebResponse, Created
from bw.error import (
    BwServerError,
    MissionDoesNotHaveMetadata,
    MissionDoesNotExist,
    NoResultFound,
    AlreadyReviewedMission,
    MissionAlreadyExists,
    MissionHasNoMap,
    HemttError,
    MissionIsNotBinarized,
)
from bw.auth.user import UserStore
from bw.missions.pbo import MissionLoader
from bw.missions.missions import MissionTypeStore, MissionStore
from bw.missions.tests import TestStore
from bw.missions.test_status import TestStatus
from bw.missions.response import (
    MissionIterationResponse,
    MissionResponse,
    MissionTypeResponse,
)
from bw.models.auth import User
from bw.settings import BW_UUID_NAMESPACE
from bw.web_event.mission import (
    MissionUploadEvent,
    IterationReviewedEvent,
    IterationCosignedEvent,
)
from bw.web_utils import define_api
from bw.server_ops.arma.server import Server


logger = logging.getLogger('bw.missions')


def name_and_version_from_name(mission_name_with_version: str) -> tuple[str, str]:
    match = re.search('_[vV][0-9]+', mission_name_with_version)
    if not match:
        return mission_name_with_version, ''

    version = match.group().strip('_')
    mission_name = mission_name_with_version[0 : match.start()]
    return mission_name, version


def uuid_from_name_and_map(mission_name: str, mission_map: str) -> UUID:
    return uuid5(namespace=BW_UUID_NAMESPACE, name=f'{mission_name}:{mission_map}')


class MissionsApi:
    @define_api
    async def upload_mission(
        self,
        state: State,
        server: Server,
        user: User,
        stored_pbo_path: Path,
        changelog: dict,
    ) -> JsonResponse:
        """
        ### Upload a mission to the database

        *Docstring generated by AI.*

        Loads a mission from a PBO directory, validates required metadata, creates or updates the mission and its
        iteration, and returns the result as a JSON response.

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `server` (`Server`): The server which to upload the mission to
        - `user` (`User`): The user uploading the mission.
        - `stored_pbo_path` (`str`): The path to the stored PBO directory.
        - `changelog` (`dict`): The changelog for this mission iteration.

        **Returns:**
        - `JsonResponse`: A JSON response containing the new iteration number, or an error message if the upload fails.

        **Example:**
        ```python
        response = await MissionsApi().upload_mission_to_main(state, token, "/missions/mission1.pbo", {"changes": "Initial"})
        # Success: JsonResponse({'iteration_number': 1, 'status': 200})
        # Error: JsonResponse({'status': 422, 'reason': 'mission does not have attached mission testing attributes'})
        # Error: JsonResponse({'status': 422, 'reason': 'no mission type with tag "{tag}" exists'})
        # Error: JsonResponse({'status': 422, 'reason': 'could not create mission iteration'})
        # Error: JsonResponse({'status': 403, 'reason': 'Session is not valid'})
        ```
        """
        if isinstance(stored_pbo_path, str):
            stored_pbo_path = Path(stored_pbo_path)

        logger.info(f'uploading mission: {stored_pbo_path} to database')
        logger.debug(f'changelog:\n\t{"\n\t".join([f"{k}: {v}" for k, v in changelog.items()])}')
        try:
            mission = await MissionLoader().load_pbo_from_directory(stored_pbo_path)
        except HemttError as err:
            error = str(err)
            if 'Invalid rapified config' in error:
                raise MissionIsNotBinarized()
            raise

        if 'potato_missiontesting_missionTestingInfo' not in mission.custom_attributes:
            raise MissionDoesNotHaveMetadata()

        info = mission.custom_attributes['potato_missiontesting_missionTestingInfo']
        if 'potato_missiontesting_missionType' not in info:
            raise MissionDoesNotHaveMetadata('mission type')

        non_versioned_mission_name, _ = name_and_version_from_name(mission.source_name)
        if stored_pbo_path.suffixes:
            mission_map = stored_pbo_path.suffixes[0].strip('.')
        else:
            mission_map = ''

        if 'pbo' in mission_map:
            raise MissionHasNoMap(stored_pbo_path.name)

        uuid = uuid_from_name_and_map(non_versioned_mission_name, mission_map)
        try:
            existing_mission = MissionStore().mission_with_uuid_in_server(state, uuid, server.server_name())
        except MissionDoesNotExist:
            existing_mission = None

        if existing_mission is None:
            tag = int(info['potato_missiontesting_missionType']['data']['value'])
            mission_type = MissionTypeStore().mission_type_from_tag(state, tag)

            flags = {}
            if 'potato_missiontesting_missionTag1' in info:
                flags['tag1'] = int(info['potato_missiontesting_missionTag1']['data']['value'])
            if 'potato_missiontesting_missionTag2' in info:
                flags['tag2'] = int(info['potato_missiontesting_missionTag2']['data']['value'])
            if 'potato_missiontesting_missionTag3' in info:
                flags['tag3'] = int(info['potato_missiontesting_missionTag3']['data']['value'])

            existing_mission = MissionStore().create_mission(
                state,
                server.server_name(),
                user,
                author=mission.author,
                title=non_versioned_mission_name,
                map=mission_map,
                type=mission_type,
                flags=flags,
                uuid=uuid,
            )

        min_players = 0
        max_players = 0
        desired_players = 0
        safe_start_length = 0
        mission_length = 0
        if 'potato_missiontesting_playerCountMinimum' in info:
            min_players = int(info['potato_missiontesting_playerCountMinimum']['data']['value'])
        if 'potato_missiontesting_playerCountMaximum' in info:
            max_players = int(info['potato_missiontesting_playerCountMaximum']['data']['value'])
        if 'potato_missiontesting_playerCountRecommended' in info:
            desired_players = int(info['potato_missiontesting_playerCountRecommended']['data']['value'])
        if 'potato_missiontesting_SSTimeGiven' in info:
            safe_start_length = int(info['potato_missiontesting_SSTimeGiven']['data']['value'])
        if 'potato_missiontesting_missionTimeLength' in info:
            mission_length = int(info['potato_missiontesting_missionTimeLength']['data']['value'])

        working_pbo_path = server.mission_path() / stored_pbo_path.name
        logger.info(f'moving mission {stored_pbo_path} to server mission folder')
        if working_pbo_path.exists():
            logger.warning('Cannot upload mission due to file already been uploaded')
            raise MissionAlreadyExists()
        shutil.copyfile(stored_pbo_path, working_pbo_path)

        iteration = MissionStore().add_iteration(
            state,
            existing_mission,
            working_pbo_path.stem,
            min_players=min_players,
            desired_players=desired_players,
            max_players=max_players,
            safe_start_length=safe_start_length,
            mission_length=mission_length,
            bwmf_version=mission.bwmf,
            changelog=changelog,
        )

        State.broker.publish(MissionUploadEvent(mission=existing_mission.uuid, iteration=iteration.uuid))
        return JsonResponse(
            {
                'iteration_number': iteration.iteration,
                'min_players': min_players,
                'max_players': max_players,
                'desired_players': desired_players,
                'safe_start_length': safe_start_length,
                'mission_length': mission_length,
            },
            status=201,
        )

    @define_api
    async def get_iteration_information(self, state: State, iteration_uuid: UUID) -> JsonResponse:
        iteration = MissionStore().iteration_with_uuid(state, iteration_uuid)
        mission = MissionStore().mission_with_iteration(state, iteration)
        mission_tag = MissionTypeStore().mission_type_from_id(state, tag_id=mission.mission_type)

        mission_tag_info = MissionTypeResponse(
            name=mission_tag.name,
            signoffs_required=mission_tag.signoffs_required,
            tag=mission_tag.numeric_tag,
        )

        if mission.author is not None:
            author_uuid = UserStore().user_from_id(state, mission.author).uuid
        else:
            author_uuid = UUID(int=0)

        mission_info = MissionResponse(
            uuid=mission.uuid,
            server=mission.server,
            creation_date=mission.creation_date,
            author_uuid=author_uuid,
            author_name=mission.author_name,
            title=mission.title,
            map=mission.map,
            mission_type=mission_tag_info,
            special_flags=mission.special_flags,
        )

        iteration_info = MissionIterationResponse(
            uuid=iteration.uuid,
            mission=mission_info,
            min_player_count=iteration.min_player_count,
            max_player_count=iteration.max_player_count,
            desired_player_count=iteration.desired_player_count,
            safe_start_length=iteration.safe_start_length,
            mission_length=iteration.mission_length,
            upload_date=iteration.upload_date,
            bwmf_version=iteration.bwmf_version,
            iteration=iteration.iteration,
            changelog=iteration.changelog,
            filename=iteration.file_name,
        )
        return JsonResponse(iteration_info)

    @define_api
    async def get_mission_information(self, state: State, mission_uuid: UUID) -> JsonResponse:
        mission = MissionStore().mission_with_uuid(state, mission_uuid)
        mission_tag = MissionTypeStore().mission_type_from_id(state, tag_id=mission.mission_type)

        mission_tag_info = MissionTypeResponse(
            name=mission_tag.name,
            signoffs_required=mission_tag.signoffs_required,
            tag=mission_tag.numeric_tag,
        )

        if mission.author is not None:
            author_uuid = UserStore().user_from_id(state, mission.author).uuid
        else:
            author_uuid = UUID(int=0)

        mission_info = MissionResponse(
            uuid=mission.uuid,
            server=mission.server,
            creation_date=mission.creation_date,
            author_uuid=author_uuid,
            author_name=mission.author_name,
            title=mission.title,
            map=mission.map,
            mission_type=mission_tag_info,
            special_flags=mission.special_flags,
        )

        return JsonResponse(mission_info)


class TestApi:
    @define_api
    async def review_mission(
        self,
        state: State,
        tester: User,
        iteration_uuid: UUID,
        status: TestStatus,
        notes: dict[str, str],
    ) -> JsonResponse:
        """
        ### Review a mission iteration

        *Docstring generated by AI.*

        Allows a user to submit a review for a mission iteration.

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `tester` (`User`): The user reviewing the mission.
        - `iteration_uuid` (`UUID`): The UUID of the mission iteration to review.
        - `status` (`TestStatus`): The status of the review.
        - `notes` (`dict[str, str]`): Notes for the review. Key:Value = `topic:review`.

        **Returns:**
        - `JsonResponse`: A JSON response containing the new result's UUID.

        **Example:**
        ```python
        response = await TestApi().review_mission(state, tester, UUID('...'), 'passed', {'note': 'good mission'})
        # Success: JsonResponse({'result_uuid': '...'})
        ```
        """
        iteration = MissionStore().iteration_with_uuid(state, iteration_uuid)
        try:
            TestStore().get_test_result_by_user(state, iteration, tester)
        except NoResultFound:
            # We want to catch this, because it means the user has not yet reviewed this iteration.
            pass
        else:
            raise AlreadyReviewedMission()

        with state.Session.begin() as session:
            review = TestStore().create_review(state, tester, status, notes)
            try:
                result = TestStore().create_result(state, iteration, review)
            except BwServerError as e:
                session.rollback()
                raise e

        State.broker.publish(IterationReviewedEvent(iteration=iteration.uuid, review=result.uuid))
        return JsonResponse({'result_uuid': result.uuid})

    @define_api
    async def cosign_result(self, state: State, tester: User, result_uuid: UUID) -> WebResponse:
        """
        ### Cosign a test result

        *Docstring generated by AI.*

        Allows a user to cosign a test result, indicating agreement with the review.

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `tester` (`User`): The user cosigning the test result.
        - `result_uuid` (`UUID`): The UUID of the test result to cosign.

        **Returns:**
        - `WebResponse`: A `Created` response on success, or an error response.

        **Example:**
        ```python
        response = await TestApi().cosign_result(state, tester, UUID('...'))
        # Success: Created()
        ```
        """
        test_result = TestStore().result_by_uuid(state, result_uuid)
        TestStore().cosign_result(state, tester, test_result)

        State.broker.publish(IterationCosignedEvent(review=test_result.uuid))
        return Created()

    @define_api
    async def reviews(self, state: State, iteration_uuid: UUID, viewer: User | None) -> JsonResponse:
        """
        ### Get reviews for a mission iteration

        *Docstring generated by AI.*

        Retrieves all reviews for a specific mission iteration. The `viewer` parameter
        is used to determine if the viewing user is the reviewer or a cosigner on any
        of the reviews.

        **Args:**
        - `state` (`State`): The application state.
        - `iteration_uuid` (`UUID`): The UUID of the mission iteration.
        - `viewer` (`User | None`): The user viewing the reviews. Can be `None` for an
          unauthenticated user.

        **Returns:**
        - `JsonResponse`: A JSON response containing a list of reviews. Each review includes
          the review's UUID, test date, status, notes, and flags indicating if the viewer
          is the reviewer or a cosigner.

        **Example:**
        ```python
        response = await TestApi().reviews(state, UUID('...'), viewer)
        # Success: JsonResponse({
        #     'reviews': [
        #         {
        #             'uuid': '...',
        #             'date_tested': '...',
        #             'status': 'passed',
        #             'notes': {'note': '...'},
        #             'is_viewer_reviewer': False,
        #             'is_viewer_cosigner': False,
        #         },
        #         ...
        #     ]
        # })
        # Error: JsonResponse({'status': 404, 'reason': 'iteration does not exist'})
        ```
        """
        iteration = MissionStore().iteration_with_uuid(state, iteration_uuid)
        reviews = TestStore().iteration_reviews(state, iteration)
        return JsonResponse(
            {
                'reviews': [
                    {
                        'uuid': str(review.uuid),
                        'date_tested': review.date_tested.isoformat(),
                        'status': str(review.status),
                        'notes': review.notes,
                        'is_viewer_reviewer': viewer is not None and viewer.id == review.original_tester_id,
                        'is_viewer_cosigner': viewer is not None and viewer.id in review.cosign_ids,
                    }
                    for review in reviews
                ]
            }
        )
