from bw.missions.test_status import TestStatus
from typing import Any
from uuid import UUID
import logging
import urllib.parse
from quart import Blueprint, render_template_string, request
from pathlib import Path

from bw.web_utils import json_endpoint, url_endpoint, html_endpoint, html_part_endpoint, load_template_from_disk
from bw.response import JsonResponse, WebResponse, NotFound
from bw.models.auth import User
from bw.auth.decorators import require_session, require_group_permission
from bw.auth.permissions import Permissions
from bw.missions.api import MissionsApi, TestApi
from bw.state import State
from bw.error import ServerConfigNotFound
from bw.server_ops.arma.server import SERVER_MAP


logger = logging.getLogger('bw.missions')


def define(api: Blueprint):
    @api.post('/upload/<string:server_name>')
    @json_endpoint
    @require_session
    @require_group_permission(Permissions.can_upload_mission)
    async def upload(
        server_name: str, session_user: User, pbo_path: str, changelog: dict[str, str], play_in_session: bool = True
    ) -> JsonResponse:
        """
        ### Upload a mission to a specific server

        *Docstring generated by AI.*

        Uploads a mission from a PBO file to the specified server. The mission metadata is logged
        and the operation is tracked. Requires an active session and `can_upload_mission` permission.

        **Args:**
        - `server_name` (`str`): The destination server for the mission upload (path parameter).
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `pbo_path` (`str`): The file path to the PBO file to upload.
        - `changelog` (`dict[str, str]`): A dictionary containing changelog entries for this upload.
        - `play_in_session` (`bool | None`): If this mission is intended to be played in session.

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}` (empty JSON object)
        - **Error (401)**: `{'status': 401, 'reason': 'Session is not valid'}`
        - **Error (403)**: `{'status': 403, 'reason': 'User does not have permission'}`
        - **Error (422)**: `{'status': 422, 'reason': 'mission does not have attached mission testing attributes'}`
        - **Error (500)**: Internal server error if mission loading fails

        **Example:**
        ```
        POST /api/v1/missions/upload/testing
        {
            "pbo_path": "/path/to/mission.pbo",
            "changelog": {
                "version": "1.0",
                "changes": "Initial release"
            }
        }
        ```
        """
        server_name = urllib.parse.unquote_plus(server_name)
        if server_name not in SERVER_MAP:
            raise ServerConfigNotFound(server_name)
        logger.info(f'User {session_user.id} is uploading mission from {pbo_path} to {server_name} with changelog: {changelog}')
        server = SERVER_MAP[server_name]
        if play_in_session:
            return await MissionsApi().upload_mission(
                state=State.state,
                server=server,
                user=session_user,
                stored_pbo_path=Path(pbo_path),
                changelog=changelog,
            )
        else:
            return MissionsApi().copy_mission_to_server(server=server, stored_pbo_path=Path(pbo_path))

    @api.get('/iteration/<uuid:iteration_uuid>')
    @url_endpoint
    @require_session
    async def get_iteration_information(iteration_uuid: UUID, session_user: User) -> JsonResponse:
        """
        ### Retrieve mission iteration information with given UUID

        Retrieves iteration information as well as mission and type information for a given UUID

        **Args:**
        - `iteration_uuid` (`UUID`): The UUID of the mission iteration (path parameter).

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}`
        **Example:**
        ```
        POST /api/v1/missions/iteration/...
        {
            "uuid": ...,
            "mission": {
                "uuid": ...,
                "server": "Main",
                "creation_date": ...,
                "author_uuid": ...,
                "author_name": "tcvm",
                "title": "tcvm_coop_20",
                "mission_type": {
                    "name": "Co-Op",
                    "signoffs_required": 1,
                    "tag": 1
                },
                "special_flags": {
                    ...
                }
            },
            "min_player_count": 15,
            "max_player_count": 40,
            "desired_player_count": 30,
            "safe_start_length": 10,
            "mission_length": 70,
            "upload_date", ...
            "bwmf_version": "1.0.0",
            "iteration": 7,
            "changelog": "blah"
        }
        ```
        """
        return await MissionsApi().get_iteration_information(State.state, iteration_uuid)

    @api.get('/mission/<uuid:mission_uuid>')
    @url_endpoint
    @require_session
    async def get_mission_information(mission_uuid: UUID, session_user: User) -> JsonResponse:
        """
        ### Retrieve mission information with given UUID

        Retrieves mission information as well as mission type information for a given UUID

        **Args:**
        - `mission_uuid` (`UUID`): The UUID of the mission (path parameter).

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}`
        **Example:**
        ```
        POST /api/v1/missions/mission/...
        {
            "uuid": ...,
            "server": "Main",
            "creation_date": ...,
            "author_uuid": ...,
            "author_name": "tcvm",
            "title": "tcvm_coop_20",
            "mission_type": {
                "name": "Co-Op",
                "signoffs_required": 1,
                "tag": 1
            },
            "special_flags": {
                ...
            }
        }
        ```
        """
        return await MissionsApi().get_mission_information(State.state, mission_uuid)


def define_html(frontend: Blueprint, parts: Blueprint):
    @frontend.get('/')
    @html_endpoint(template_path='missions/index.html', title='BW Missions')
    async def homepage(html: str) -> str:
        mission_count = MissionsApi().mission_count(State.state)
        return await render_template_string(html, mission_count=mission_count)

    @parts.get('/list')
    @html_part_endpoint(template_path='missions/mission_card.bundle.html')
    async def list(html: str) -> str | WebResponse:
        current_page = int(request.args.get('page', '1'))
        current_page = max(1, current_page)
        items_per_page = int(request.args.get('count_per_page', '10'))
        items_per_page = max(10, items_per_page)

        if (current_page - 1) * items_per_page > MissionsApi().mission_count(State.state):
            return NotFound()

        card_template = load_template_from_disk(template_path='missions/mission_card.template.html')
        mission_cards = []

        for mission in MissionsApi().get_missions_by_page(State.state, page=current_page, items_per_page=items_per_page):
            iterations_for_mission = sorted(
                MissionsApi().iterations_for_mission(State.state, mission.uuid),
                key=lambda iteration: iteration.upload_date,
                reverse=True,
            )
            if iterations_for_mission:
                latest_iteration = iterations_for_mission[0]
                reviews: list[dict[str, Any]] = (await TestApi().reviews(State.state, latest_iteration.uuid, viewer=None))[
                    'reviews'
                ]
                passes = sum([(1 + review['cosigns']) for review in reviews if TestStatus(review['status']) == TestStatus.PASSED])
                fails = sum([(1 + review['cosigns']) for review in reviews if TestStatus(review['status']) == TestStatus.FAILED])
            else:
                passes = 0
                fails = 0
            mission_cards.append(
                await render_template_string(
                    card_template,
                    mission_type=mission.mission_type.name,
                    mission_name=mission.title,
                    mission_author=mission.author_name,
                    mission_map=mission.map,
                    mission_uuid=mission.uuid,
                    iteration_count=len(iterations_for_mission),
                    signed_off=(passes - 2 * fails) == mission.mission_type.signoffs_required,
                    passed_signoffs=passes,
                    failed_signoffs=fails,
                    needed_signoffs=mission.mission_type.signoffs_required,
                )
            )

        return await render_template_string(html, mission_cards=mission_cards, page_number=current_page + 1)
