from uuid import UUID
import logging
import urllib.parse
from quart import render_template_string, Blueprint
from pathlib import Path

from bw.web_utils import json_endpoint, url_endpoint, html_endpoint
from bw.response import JsonResponse
from bw.models.auth import User
from bw.auth.decorators import require_session, require_group_permission
from bw.auth.permissions import Permissions
from bw.missions.api import MissionsApi
from bw.state import State
from bw.error import ServerConfigNotFound
from bw.server_ops.arma.server import SERVER_MAP


logger = logging.getLogger('bw.missions')


def define(api: Blueprint, local: Blueprint, html: Blueprint):
    @api.post('/upload/<string:server_name>')
    @json_endpoint
    @require_session
    @require_group_permission(Permissions.can_upload_mission)
    async def upload(
        server_name: str, session_user: User, pbo_path: str, changelog: dict[str, str], play_in_session: bool | None = None
    ) -> JsonResponse:
        """
        ### Upload a mission to a specific server

        *Docstring generated by AI.*

        Uploads a mission from a PBO file to the specified server. The mission metadata is logged
        and the operation is tracked. Requires an active session and `can_upload_mission` permission.

        **Args:**
        - `server_name` (`str`): The destination server for the mission upload (path parameter).
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `pbo_path` (`str`): The file path to the PBO file to upload.
        - `changelog` (`dict[str, str]`): A dictionary containing changelog entries for this upload.
        - `play_in_session` (`bool | None`): If this mission is intended to be played in session.

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}` (empty JSON object)
        - **Error (401)**: `{'status': 401, 'reason': 'Session is not valid'}`
        - **Error (403)**: `{'status': 403, 'reason': 'User does not have permission'}`
        - **Error (422)**: `{'status': 422, 'reason': 'mission does not have attached mission testing attributes'}`
        - **Error (500)**: Internal server error if mission loading fails

        **Example:**
        ```
        POST /api/v1/missions/upload/testing
        {
            "pbo_path": "/path/to/mission.pbo",
            "changelog": {
                "version": "1.0",
                "changes": "Initial release"
            }
        }
        ```
        """
        server_name = urllib.parse.unquote_plus(server_name)
        if server_name not in SERVER_MAP:
            raise ServerConfigNotFound(server_name)
        logger.info(f'User {session_user.id} is uploading mission from {pbo_path} to {server_name} with changelog: {changelog}')
        server = SERVER_MAP[server_name]
        if play_in_session:
            return await MissionsApi().upload_mission(
                state=State.state,
                server=server,
                user=session_user,
                stored_pbo_path=Path(pbo_path),
                changelog=changelog,
            )
        else:
            return MissionsApi().copy_mission_to_server(server=server, stored_pbo_path=Path(pbo_path))

    @api.get('/iteration/<uuid:iteration_uuid>')
    @url_endpoint
    @require_session
    async def get_iteration_information(iteration_uuid: UUID, session_user: User) -> JsonResponse:
        """
        ### Retrieve mission iteration information with given UUID

        Retrieves iteration information as well as mission and type information for a given UUID

        **Args:**
        - `iteration_uuid` (`UUID`): The UUID of the mission iteration (path parameter).

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}`
        **Example:**
        ```
        POST /api/v1/missions/iteration/...
        {
            "uuid": ...,
            "mission": {
                "uuid": ...,
                "server": "Main",
                "creation_date": ...,
                "author_uuid": ...,
                "author_name": "tcvm",
                "title": "tcvm_coop_20",
                "mission_type": {
                    "name": "Co-Op",
                    "signoffs_required": 1,
                    "tag": 1
                },
                "special_flags": {
                    ...
                }
            },
            "min_player_count": 15,
            "max_player_count": 40,
            "desired_player_count": 30,
            "safe_start_length": 10,
            "mission_length": 70,
            "upload_date", ...
            "bwmf_version": "1.0.0",
            "iteration": 7,
            "changelog": "blah"
        }
        ```
        """
        return await MissionsApi().get_iteration_information(State.state, iteration_uuid)

    @api.get('/mission/<uuid:mission_uuid>')
    @url_endpoint
    @require_session
    async def get_mission_information(mission_uuid: UUID, session_user: User) -> JsonResponse:
        """
        ### Retrieve mission information with given UUID

        Retrieves mission information as well as mission type information for a given UUID

        **Args:**
        - `mission_uuid` (`UUID`): The UUID of the mission (path parameter).

        **Returns:**
        - `JsonResponse`:
        - **Success (200)**: `{}`
        **Example:**
        ```
        POST /api/v1/missions/mission/...
        {
            "uuid": ...,
            "server": "Main",
            "creation_date": ...,
            "author_uuid": ...,
            "author_name": "tcvm",
            "title": "tcvm_coop_20",
            "mission_type": {
                "name": "Co-Op",
                "signoffs_required": 1,
                "tag": 1
            },
            "special_flags": {
                ...
            }
        }
        ```
        """
        return await MissionsApi().get_mission_information(State.state, mission_uuid)

    @html.get('/')
    @html_endpoint(template_path='home.html', title='Bourbon Warfare')
    async def html_home(html: str) -> str:
        """
        ### Home page

        *Docstring generated by AI.*

        Renders the main home page of the Bourbon Warfare application.

        **Args:**
        - `html` (`str`): The HTML template content (automatically injected by `@html_endpoint`).

        **Returns:**
        - `str`: HTML content of the home page.

        **Example:**
        ```
        GET /
        ```
        Returns the rendered HTML home page.
        """
        return await render_template_string(
            html,
        )
