from bw.state import State
from bw.response import JsonResponse, Ok, WebResponse, Exists, DoesNotExist
from bw.auth.session import SessionStore
from bw.auth.user import UserStore
from bw.auth.group import GroupStore
from bw.auth.roles import Roles
from bw.auth.permissions import Permissions
from bw.models.auth import User
from bw.error import BwServerError, SessionExpired
from bw.web_utils import define_api, define_async_api
from bw.environment import ENVIRONMENT
from bw.error import ReauthNeededError, AuthError, NoUserWithGivenCredentials
import uuid
import aiohttp


class AuthApi:
    @define_api
    def create_new_user_bot(self, state: State) -> JsonResponse:
        """
        ### Create a new user and link a bot user

        Creates a new user and links a bot user to it, returning the bot token.
        Rolls back the transaction and returns an error response if user or bot creation fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Returns:**
        - `JsonResponse`: A JSON response containing the bot token or an error message.

        **Example:**
        ```python
        response = AuthApi().create_new_user_bot(state)
        # Success: JsonResponse({'bot_token': 'potato', 'status': 201})
        # Error: WebResponse(status=400, reason='An internal error occurred')
        ```
        """
        with state.Session.begin() as session:
            with session.begin_nested() as savepoint:
                user = UserStore().create_user(state)
                try:
                    bot = UserStore().link_bot_user(state, user)
                except BwServerError as e:
                    savepoint.rollback()
                    raise e
        return JsonResponse({'bot_token': bot.bot_token}, status=201)

    @define_async_api
    async def login_with_discord(self, state: State, token: str) -> JsonResponse:
        """
        ### Log in with Discord access token

        Logs in a user via their Discord access token. Retrieves the user's information from Discord,
        creates a new user if they don't exist, and starts a new session for them.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `token` (`str`): The access token provided by the Discord OAuth API.

        **Returns:**
        - `JsonResponse`: A JSON response containing session information or an error message.

        **Example:**
        ```python
        response = await AuthApi().login_with_discord(state, 'discord_access_token')
        # Success: JsonResponse({
        #   'session_token': 'potato',
        #   'expire_time': '1999-12-23T00:00:00Z',
        #   'status': 200
        # })
        # Error: WebResponse(status=401, reason='Access token has expired')
        ```
        """
        headers = {'Authorization': f'Bearer {token}'}
        async with aiohttp.ClientSession(headers=headers) as session:
            async with session.get(f'{ENVIRONMENT.discord_api_url()}/users/@me') as response:
                try:
                    response.raise_for_status()
                except aiohttp.ClientResponseError as e:
                    if e.status == 401:
                        raise ReauthNeededError(e.message, 'Discord OAuth')
                    raise AuthError(e.message)

                user = await response.json()

        print(user)
        discord_id = user['id']
        try:
            user = UserStore().user_from_discord_id(state, discord_id)
        except NoUserWithGivenCredentials:
            user = UserStore().create_user(state)
            UserStore().link_discord_user(state, discord_id, user)
        return JsonResponse(SessionStore().start_user_session(state, user))

    @define_api
    def login_with_bot(self, state: State, bot_token: str) -> JsonResponse:
        """
        ### Log in with bot token

        Logs in a user using their bot token and starts a new API session for them.
        Returns an error response if the user does not exist.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `bot_token` (`str`): The bot token of the user to log in.

        **Returns:**
        - `JsonResponse`: A JSON response containing session information or an error message.

        **Example:**
        ```python
        response = AuthApi().login_with_bot(state, 'potato')
        # Success: JsonResponse({
        #   'session_token': 'potato',
        #   'expire_time': '1999-12-23T00:00:00Z',
        #   'status': 200
        # })
        # Error: WebResponse(status=404, reason='User does not exist')
        ```
        """
        user = UserStore().user_from_bot_token(state, bot_token)
        return JsonResponse(SessionStore().start_api_session(state, user))

    @define_api
    def is_session_active(self, state: State, session_token: str) -> Exists:
        """
        ### Check if a session is active

        Checks if a session with the given token is currently active (not expired or revoked).

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `session_token` (`str`): The session token to check.

        **Returns:**
        - `Exists`: An Exists response (200) if session is active, DoesNotExist response (409) otherwise.

        **Example:**
        ```python
        response = AuthApi().is_session_active(state, 'potato')
        # Success: Exists() (status 200, message 'Exists')
        # Not active: DoesNotExist() (status 409, message 'Does not exist')
        ```
        """
        return Exists(SessionStore().is_session_active(state, session_token))

    @define_api
    def does_user_have_roles(self, state: State, session_token: str, wanted_roles: Roles) -> Exists:
        """
        ### Check if user has all specified roles

        Checks if the user associated with the session token has all the specified roles.
        Returns DoesNotExist if the session is invalid, the user has no roles, or any required role
        is missing.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `session_token` (`str`): The session token of the user.
        - `wanted_roles` (`Roles`): The roles to check for.

        **Returns:**
        - `Exists`: An Exists response (200) if user has all roles, DoesNotExist response (409) otherwise.

        **Example:**
        ```python
        response = AuthApi().does_user_have_roles(state, 'potato', wanted_roles)
        # Success: Exists() (status 200, message 'Exists')
        # Missing roles: DoesNotExist() (status 409, message 'Does not exist')
        ```
        """
        try:
            user = SessionStore().get_user_from_session_token(state, session_token)
        except SessionExpired:
            return DoesNotExist()

        user_roles = UserStore().get_users_role(state, user)
        if user_roles is None:
            return DoesNotExist()

        test_roles = user_roles.as_dict()
        for role, expecting_role in wanted_roles.as_dict().items():
            if expecting_role and not test_roles[role]:
                return DoesNotExist()
        return Exists()

    @define_api
    def does_user_have_permissions(self, state: State, session_token: str, wanted_perms: Permissions) -> Exists:
        """
        ### Check if user has all specified permissions

        Checks if the user associated with the session token has all the specified permissions through
        their group memberships. Returns DoesNotExist if the session is invalid, the user has no
        permissions, or any required permission is missing.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `session_token` (`str`): The session token of the user.
        - `wanted_perms` (`Permissions`): The permissions to check for.

        **Returns:**
        - `Exists`: An Exists response (200) if user has all permissions, DoesNotExist response (409)
        otherwise.

        **Example:**
        ```python
        response = AuthApi().does_user_have_permissions(state, 'potato', wanted_perms)
        # Success: Exists() (status 200, message 'Exists')
        # Missing permissions: DoesNotExist() (status 409, message 'Does not exist')
        ```
        """
        try:
            user = SessionStore().get_user_from_session_token(state, session_token)
        except SessionExpired:
            return DoesNotExist()

        user_perms = GroupStore().get_all_permissions_user_has(state, user)
        if user_perms is None:
            return DoesNotExist()

        test_perms = user_perms.as_dict()
        for perms, expecting_perms in wanted_perms.as_dict().items():
            if expecting_perms and not test_perms[perms]:
                return DoesNotExist()
        return Exists()

    @define_api
    def revoke_discord_user_session(self, state: State, discord_id: int) -> WebResponse:
        """
        ### Revoke all sessions for a Discord user

        Revokes (expires) all active sessions for the user associated with the given Discord ID.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `discord_id` (`int`): The Discord ID of the user whose sessions should be revoked.

        **Returns:**
        - `Ok`: An OK response indicating the user's sessions have been revoked, or an error response
        if the user does not exist.

        **Example:**
        ```python
        response = AuthApi().revoke_discord_user_session(state, 123456)
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='User does not exist')
        ```
        """
        user = UserStore().user_from_discord_id(state, discord_id)
        SessionStore().expire_session_from_user(state, user)
        return Ok()

    @define_api
    def revoke_bot_user_session(self, state: State, bot_token: str) -> WebResponse:
        """
        ### Revoke all sessions for a bot user

        Revokes (expires) all active sessions for the user associated with the given bot token.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `bot_token` (`str`): The bot token of the user whose sessions should be revoked.

        **Returns:**
        - `Ok`: An OK response indicating the user's sessions have been revoked, or an error response
        if the user does not exist.

        **Example:**
        ```python
        response = AuthApi().revoke_bot_user_session(state, 'potato')
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='User does not exist')
        ```
        """
        user = UserStore().user_from_bot_token(state, bot_token)
        SessionStore().expire_session_from_user(state, user)
        return Ok()

    @define_api
    def create_role(self, state: State, role_name: str, roles: Roles) -> JsonResponse:
        """
        ### Create a new role

        Creates a new role with the specified name and role permissions.
        Returns an error response if role creation fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `role_name` (`str`): The name of the role to create.
        - `roles` (`Roles`): The role permissions to assign.

        **Returns:**
        - `JsonResponse`: A JSON response containing the role name or an error message.

        **Example:**
        ```python
        response = AuthApi().create_role(state, 'admin', roles)
        # Success: JsonResponse({'name': 'admin', 'status': 201})
        # Error: WebResponse(status=409, reason='Creation of role "admin" failed.')
        ```
        """
        role = UserStore().create_role(state, role_name=role_name, roles=roles)
        return JsonResponse({'name': role.name}, status=201)

    @define_api
    def assign_role(self, state: State, role_name: str, user_uuid: uuid.UUID) -> WebResponse:
        """
        ### Assign a role to a user

        Assigns the specified role to the user with the given UUID.
        Returns an error response if the user does not exist or role assignment fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `role_name` (`str`): The name of the role to assign.
        - `user_uuid` (`uuid.UUID`): The UUID of the user to assign the role to.

        **Returns:**
        - `Ok`: An OK response if successful, or an error response if failed.

        **Example:**
        ```python
        response = AuthApi().assign_role(state, 'admin', user_uuid)
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='User does not exist')
        ```
        """
        user = UserStore().user_from_uuid(state, uuid=user_uuid)
        UserStore().assign_user_role(state, user=user, role_name=role_name)
        return Ok()

    @define_api
    def create_group_permission(self, state: State, permission_name: str, permissions: Permissions) -> JsonResponse:
        """
        ### Create a new group permission

        Creates a new group permission with the specified name and permission settings.
        Returns an error response if permission creation fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `permission_name` (`str`): The name of the permission to create.
        - `permissions` (`Permissions`): The permission settings to assign.

        **Returns:**
        - `JsonResponse`: A JSON response containing the permission name or an error message.

        **Example:**
        ```python
        response = AuthApi().create_group_permission(state, 'read_access', permissions)
        # Success: JsonResponse({'name': 'read_access', 'status': 201})
        # Error: WebResponse(status=409, reason='Creation of permission "read_access" failed.')
        ```
        """
        permission = GroupStore().create_permission(state, name=permission_name, permissions=permissions)
        return JsonResponse({'name': permission.name}, status=201)

    @define_api
    def create_group(self, state: State, group_name: str, permission_group: str) -> JsonResponse:
        """
        ### Create a new group

        Creates a new group with the specified name and associated permissions.
        Returns an error response if group creation fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `group_name` (`str`): The name of the group to create.
        - `permission_group` (`str`): The name of the permission group to associate.

        **Returns:**
        - `JsonResponse`: A JSON response containing the group name or an error message.

        **Example:**
        ```python
        response = AuthApi().create_group(state, 'editors', 'edit_permissions')
        # Success: JsonResponse({'name': 'editors', 'status': 201})
        # Error: WebResponse(status=409, reason='Creation of group "editors" failed.')
        ```
        """
        group = GroupStore().create_group(state=state, group_name=group_name, permission_group=permission_group)
        return JsonResponse({'name': group.name}, status=201)

    @define_api
    def join_group(self, state: State, user: User, group_name: str) -> WebResponse:
        """
        ### Join a group

        Adds the specified user to the given group.
        Returns an error response if the group does not exist or assignment fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `user` (`User`): The user object to add to the group.
        - `group_name` (`str`): The name of the group to join.

        **Returns:**
        - `Ok`: An OK response if successful, or an error response if failed.

        **Example:**
        ```python
        response = AuthApi().join_group(state, user, 'editors')
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='Group does not exist')
        ```
        """
        group = GroupStore().get_group(state=state, group_name=group_name)
        GroupStore().assign_user_to_group(state=state, user=user, group=group)
        return Ok()

    @define_api
    def leave_group(self, state: State, user: User, group_name: str) -> WebResponse:
        """
        ### Leave a group

        Removes the specified user from the given group.
        Returns an error response if the group does not exist or removal fails.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `user` (`User`): The user object to remove from the group.
        - `group_name` (`str`): The name of the group to leave.

        **Returns:**
        - `Ok`: An OK response if successful, or an error response if failed.

        **Example:**
        ```python
        response = AuthApi().leave_group(state, user, 'editors')
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='Group does not exist')
        ```
        """
        group = GroupStore().get_group(state=state, group_name=group_name)
        GroupStore().remove_user_from_group(state=state, user=user, group=group)
        return Ok()

    @define_api
    def user_info(self, state: State, user: User) -> JsonResponse:
        """
        ### Get public user information

        Returns all information that is publicly available for a user, including roles, groups,
        UUID, creation date, and other relevant details.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `user` (`User`): The user object to retrieve public information for.

        **Returns:**
        - `JsonResponse`: A JSON response containing the public information for the user.

        **Example:**
        ```python
        response = AuthApi().user_info(state, user)
        # Success: JsonResponse({
        #   'uuid': '12345678-1234-5678-9012-123456789012',
        #   'creation_date': '2023-01-01T00:00:00',
        #   'groups': ['mission makers', 'mission testers']
        # })
        ```
        """
        public_info = {
            'uuid': str(user.uuid),
            'creation_date': user.creation_date.isoformat(),
            'groups': [group.name for group in GroupStore().get_user_groups(state, user)],
        }
        return JsonResponse(public_info)

    @define_api
    def register_access_code(self, state: State, code: str, code_state: str) -> WebResponse:
        """
        ### Register Discord OAuth access code

        Stores a Discord OAuth access code in the database to be retrieved later during the
        authentication flow. The code has a short expiry time.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `code` (`str`): The access code provided by the Discord OAuth flow.
        - `code_state` (`str`): The state parameter provided by the Discord OAuth flow.

        **Returns:**
        - `Ok`: An OK response indicating the code was registered successfully.

        **Example:**
        ```python
        response = AuthApi().register_access_code(state, 'oauth_code', 'state_value')
        # Success: Ok() (status 200)
        ```
        """
        SessionStore().register_discord_oauth_code(state, code, code_state)
        return Ok()

    @define_api
    def retrieve_access_code(self, state: State, code_state: str) -> JsonResponse:
        """
        ### Retrieve Discord OAuth access code

        Retrieves a previously stored Discord OAuth access code using its state parameter.
        The code is deleted after retrieval.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `code_state` (`str`): The state parameter from the Discord OAuth flow.

        **Returns:**
        - `JsonResponse`: A JSON response containing the access code or an error message.

        **Example:**
        ```python
        response = AuthApi().retrieve_access_code(state, 'state_value')
        # Success: JsonResponse({'access_code': 'oauth_code'})
        # Error: WebResponse(status=404, reason='No access code was found.')
        ```
        """
        return JsonResponse({'access_code': SessionStore().get_discord_oauth_code(state, code_state)})

    @define_api
    def list_all_users(self, state: State, page: int = 1, page_size: int = 50) -> JsonResponse:
        """
        ### List all users with pagination

        Retrieves a paginated list of all users with their basic information, roles, groups,
        and connected apps.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `page` (`int`): The page number to retrieve (default: 1).
        - `page_size` (`int`): Number of users per page (default: 50).

        **Returns:**
        - `JsonResponse`: A JSON response containing paginated user list and metadata.

        **Example:**
        ```python
        response = AuthApi().list_all_users(state, page=1, page_size=50)
        # Success: JsonResponse({
        #   'users': [...],
        #   'total': 150,
        #   'page': 1,
        #   'page_size': 50
        # })
        ```
        """
        users_data = UserStore().get_all_users_paginated(state, page=page, page_size=page_size)
        return JsonResponse(users_data)

    @define_api
    def get_all_roles(self, state: State) -> JsonResponse:
        """
        ### Get all roles

        Retrieves all roles in the system with their permission settings.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Returns:**
        - `JsonResponse`: A JSON response containing all roles.

        **Example:**
        ```python
        response = AuthApi().get_all_roles(state)
        # Success: JsonResponse({
        #   'roles': [
        #     {'name': 'admin', 'can_create_role': True, 'can_create_group': True},
        #     {'name': 'user', 'can_create_role': False, 'can_create_group': False}
        #   ]
        # })
        ```
        """
        roles = UserStore().get_all_roles(state)
        roles_data = [{'name': role.name, **role.into_roles().as_dict()} for role in roles]
        return JsonResponse({'roles': roles_data})

    @define_api
    def get_all_permissions(self, state: State) -> JsonResponse:
        """
        ### Get all group permissions

        Retrieves all group permissions in the system.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Returns:**
        - `JsonResponse`: A JSON response containing all group permissions.

        **Example:**
        ```python
        response = AuthApi().get_all_permissions(state)
        # Success: JsonResponse({
        #   'permissions': [
        #     {'name': 'read_access', 'can_upload_mission': False},
        #     {'name': 'write_access', 'can_upload_mission': True}
        #   ]
        # })
        ```
        """
        permissions = GroupStore().get_all_permissions(state)
        perms_data = [{'name': perm.name, **perm.into_permissions().as_dict()} for perm in permissions]
        return JsonResponse({'permissions': perms_data})

    @define_api
    def get_all_groups(self, state: State) -> JsonResponse:
        """
        ### Get all groups

        Retrieves all groups in the system with their associated permissions.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Returns:**
        - `JsonResponse`: A JSON response containing all groups.

        **Example:**
        ```python
        response = AuthApi().get_all_groups(state)
        # Success: JsonResponse({
        #   'groups': [
        #     {'id': 1, 'name': 'editors', 'permissions': 2},
        #     {'id': 2, 'name': 'viewers', 'permissions': 1}
        #   ]
        # })
        ```
        """
        groups = GroupStore().get_all_groups(state)
        groups_data = [{'id': group.id, 'name': group.name, 'permissions': group.permissions} for group in groups]
        return JsonResponse({'groups': groups_data})

    @define_api
    def delete_role(self, state: State, role_name: str) -> WebResponse:
        """
        ### Delete a role

        Deletes the specified role and removes it from all users.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `role_name` (`str`): The name of the role to delete.

        **Returns:**
        - `Ok`: An OK response if successful, or an error response if failed.

        **Example:**
        ```python
        response = AuthApi().delete_role(state, 'admin')
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='No role with name "admin" exists.')
        ```
        """
        UserStore().delete_role(state, role_name=role_name)
        return Ok()

    @define_api
    def delete_permission(self, state: State, permission_name: str) -> WebResponse:
        """
        ### Delete a group permission

        Deletes the specified group permission.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `permission_name` (`str`): The name of the permission to delete.

        **Returns:**
        - `Ok`: An OK response if successful, or an error response if failed.

        **Example:**
        ```python
        response = AuthApi().delete_permission(state, 'read_access')
        # Success: Ok() (status 200)
        # Error: WebResponse(status=404, reason='No group permission called "read_access" exists.')
        ```
        """
        GroupStore().delete_permission(state, permission_name=permission_name)
        return Ok()

    @define_api
    def delete_group(self, state: State, group_name: str) -> WebResponse:
        """
        ### Delete a group

        Deletes the specified group and all user associations.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `group_name` (`str`): The name of the group to delete.

        **Returns:**
        - `Ok`: An OK response if successful.

        **Example:**
        ```python
        response = AuthApi().delete_group(state, 'editors')
        # Success: Ok() (status 200)
        ```
        """
        GroupStore().delete_group(state, group_name=group_name)
        return Ok()

    @define_api
    def edit_role(self, state: State, role_name: str, roles: Roles) -> JsonResponse:
        """
        ### Edit a role

        Updates the permissions for an existing role.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `role_name` (`str`): The name of the role to edit.
        - `roles` (`Roles`): The new role permissions to assign.

        **Returns:**
        - `JsonResponse`: A JSON response containing the updated role name.

        **Example:**
        ```python
        response = AuthApi().edit_role(state, 'admin', roles)
        # Success: JsonResponse({'name': 'admin'})
        # Error: WebResponse(status=404, reason='No role with name "admin" exists.')
        ```
        """
        role = UserStore().edit_role(state, role_name=role_name, new_roles=roles)
        return JsonResponse({'name': role.name})

    @define_api
    def edit_permission(self, state: State, permission_name: str, permissions: Permissions) -> JsonResponse:
        """
        ### Edit a group permission

        Updates the permission settings for an existing group permission.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `permission_name` (`str`): The name of the permission to edit.
        - `permissions` (`Permissions`): The new permission settings to assign.

        **Returns:**
        - `JsonResponse`: A JSON response containing the updated permission name.

        **Example:**
        ```python
        response = AuthApi().edit_permission(state, 'read_access', permissions)
        # Success: JsonResponse({'name': 'read_access'})
        # Error: WebResponse(status=404, reason='No group permission called "read_access" exists.')
        ```
        """
        permission = GroupStore().edit_permission(state, permission_name=permission_name, permissions=permissions)
        return JsonResponse({'name': permission.name})
