import logging
import uuid
import secrets
from quart import Blueprint, request

from bw.web_utils import json_endpoint, url_endpoint, html_endpoint
from bw.response import JsonResponse, WebResponse
from bw.models.auth import User
from bw.auth.decorators import require_session, require_local, require_user_role, with_token
from bw.auth.permissions import Permissions
from bw.auth.roles import Roles
from bw.auth.api import AuthApi
from bw.state import State


logger = logging.getLogger('bw.auth')

"""
Authentication & Authorization Endpoints Summary:

API Endpoints:
- GET /auth/login/discord - Endpoint for Discord OAuth2 login flow
- POST /api/v1/auth/login/bot - Authenticate bot user and create API session
- GET /api/v1/user/ - Get authenticated user information
- POST /api/v1/user/role/create - Create a new role (requires can_create_role)
- POST /api/v1/user/role/assign - Assign role to user (requires can_create_role)
- POST /api/v1/group/create/permission - Create group permission (requires can_create_group)
- POST /api/v1/group/create - Create new group (requires can_create_group)
- POST /api/v1/group/join - Join a group
- POST /api/v1/group/leave - Leave a group

Local Endpoints:
- POST /api/local/user/create/bot - Create new bot user (local only)
- POST /api/local/user/role/create - Create role (local only, requires session)
- POST /api/local/user/role/assign - Assign role to user (local only, requires session)
"""


def define_auth(api: Blueprint, local: Blueprint, html: Blueprint):
    @html.get('/login/discord')
    @html_endpoint(template_path='auth/discord.html', title='Logged in with Discord')
    async def login_discord_redirect(html: str) -> str:
        """
        ### Discord OAuth2 redirect endpoint

        Receives the OAuth2 redirect from Discord and stores the access code in the database.
        The client will then request the access code using the state parameter to complete
        authentication.

        *Docstring generated by AI.*

        **Args:**
        - `html` (`str`): The HTML template content (automatically injected by `@html_endpoint`).
        - `code` (`str`): The access code from Discord OAuth (query parameter).
        - `state` (`str`): The state parameter from Discord OAuth (query parameter).

        **Returns:**
        - `HtmlResponse`: HTML response with content-type 'text/html'
          - **Success (200)**: Rendered HTML page indicating successful authentication

        **Example:**
        ```
        GET /login/discord?code=discord_oauth_code&state=random_state_token
        ```
        """
        code = request.args.get('code', default='', type=str)
        state = request.args.get('state', default=secrets.token_urlsafe(32), type=str)
        logger.info('OAuth redirect (Discord)')
        try:
            AuthApi().register_access_code(state=State.state, code=code, code_state=state)
        finally:
            return html

    @api.get('/login/discord/<string:state>')
    @url_endpoint
    async def get_discord_access_code(state: str) -> JsonResponse:
        """
        ### Retrieve Discord OAuth access code

        Returns the access code associated with the state parameter from the OAuth flow.
        The access code is deleted after retrieval.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`str`): The state parameter from the Discord OAuth flow (path parameter).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'access_code': 'discord_oauth_code'}`
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/auth/login/discord/random_state_token
        ```
        """
        logger.info('Retrieving access code (Discord)')
        return AuthApi().retrieve_access_code(state=State.state, code_state=state)

    @api.post('/login/discord')
    @json_endpoint
    @with_token
    async def login_discord(token) -> JsonResponse:
        """
        ### Log in with Discord access token

        Authenticates a Discord user using their access token and creates a new session.
        If the access token is expired or invalid, returns a 401 error with reauth URL.

        *Docstring generated by AI.*

        **Args:**
        - `token` (`str`): The Discord access token (automatically extracted from Authorization header by
        `@with_token`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'session_token': 'abc123...', 'expire_time': '2024-12-31T23:59:59'}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/auth/login/discord
        Authorization: Bearer discord_access_token_here
        ```
        """
        logger.info('Creating new session (Discord)')
        return await AuthApi().login_with_discord(state=State.state, token=token)

    @api.post('/login/bot')
    @json_endpoint
    async def login_bot(bot_token: str) -> JsonResponse:
        """
        ### Log in with bot token

        Authenticates a bot user and creates a new API session.

        *Docstring generated by AI.*

        **Args:**
        - `bot_token` (`str`): The bot token for authentication.

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'session_token': 'abc123...', 'expire_time': '2024-12-31T23:59:59'}`
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/auth/login/bot
        {
            "bot_token": "your_bot_token_here"
        }
        ```
        """
        logger.info('Creating new session (bot)')
        return AuthApi().login_with_bot(state=State.state, bot_token=bot_token)


def define_user(api: Blueprint, local: Blueprint, html: Blueprint):
    local_role_blueprint = Blueprint('local_role', __name__, url_prefix='/role')
    role_blueprint = Blueprint('role', __name__, url_prefix='/role')

    @api.get('/')
    @url_endpoint
    @require_session
    async def get_user_info(session_user: User) -> JsonResponse:
        """
        ### Get authenticated user information

        Retrieves public information about the authenticated user, including UUID, creation date,
        and group memberships.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'uuid': '12345678-1234-5678-9012-123456789012',
          'creation_date': '2023-01-01T00:00:00',
          'groups': ['group1', 'group2']
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/user/
        ```
        """
        return AuthApi().user_info(state=State.state, user=session_user)

    @role_blueprint.post('/create')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def create_role(session_user: User, role_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new role

        Creates a new role with the specified name and role permissions.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to create.
        - `**kwargs`: Role permissions as key-value pairs (e.g., `can_create_group=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'moderator', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/user/role/create
        {
            "role_name": "moderator",
            "can_create_group": true,
            "can_manage_users": false
        }
        ```
        """
        logger.info('Creating new role')
        role = Roles.from_keys(**kwargs)
        return AuthApi().create_role(State.state, role_name=role_name, roles=role)

    @role_blueprint.post('/assign')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def assign_role(session_user: User, role_name: str, user_uuid: str) -> WebResponse:
        """
        ### Assign a role to a user

        Assigns the specified role to the user with the given UUID.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to assign.
        - `user_uuid` (`str`): The UUID of the user to assign the role to.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/user/role/assign
        {
            "role_name": "moderator",
            "user_uuid": "12345678-1234-5678-9012-123456789012"
        }
        ```
        """
        logger.info(f'Assigning {role_name} to user {user_uuid}')
        return AuthApi().assign_role(State.state, role_name=role_name, user_uuid=uuid.UUID(hex=user_uuid))

    # required to bootstrap server
    @local.post('/create/bot')
    @url_endpoint
    @require_local
    async def local_create_bot() -> JsonResponse:
        """
        ### Create a new bot user (Local only)

        Creates a new user and links a bot user to it, returning the bot token.
        This endpoint is only available for local requests (internal server bootstrapping).

        *Docstring generated by AI.*

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'bot_token': 'abc123...', 'status': 201}`
          - **Error (400)**: HTTP 400 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/create/bot
        ```
        """
        logger.info('Creating new bot user (Local)')
        return AuthApi().create_new_user_bot(state=State.state)

    @local_role_blueprint.post('/create')
    @json_endpoint
    @require_local
    @require_session
    async def local_create_role(session_user: User, role_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new role (Local only)

        Creates a new role with the specified name and role permissions.
        This endpoint is only available for local requests (internal server administration).

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to create.
        - `**kwargs`: Role permissions as key-value pairs (e.g., `can_create_group=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'admin', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/role/create
        {
            "role_name": "admin",
            "can_create_group": true,
            "can_manage_users": true
        }
        ```
        """
        logger.info('Creating new role (Local)')
        role = Roles.from_keys(**kwargs)
        return AuthApi().create_role(State.state, role_name=role_name, roles=role)

    @local_role_blueprint.post('/assign')
    @json_endpoint
    @require_local
    @require_session
    async def local_assign_role(session_user: User, role_name: str, user_uuid: str) -> WebResponse:
        """
        ### Assign a role to a user (Local only)

        Assigns the specified role to the user with the given UUID.
        This endpoint is only available for local requests (internal server administration).

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to assign.
        - `user_uuid` (`str`): The UUID of the user to assign the role to.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/role/assign
        {
            "role_name": "admin",
            "user_uuid": "12345678-1234-5678-9012-123456789012"
        }
        ```
        """
        logger.info(f'Assigning {role_name} to user {user_uuid} (Local)')
        return AuthApi().assign_role(State.state, role_name=role_name, user_uuid=uuid.UUID(hex=user_uuid))

    api.register_blueprint(role_blueprint)
    local.register_blueprint(local_role_blueprint)


def define_group(api: Blueprint, local: Blueprint, html: Blueprint):
    @api.post('/create/permission')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def create_group_permission(session_user: User, permission_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new group permission

        Creates a new group permission with the specified name and permission settings.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `permission_name` (`str`): The name of the permission to create.
        - `**kwargs`: Permission settings as key-value pairs (e.g., `can_read=True`, `can_write=False`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'read_access', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/create/permission
        {
            "permission_name": "read_access",
            "can_read": true,
            "can_write": false,
            "can_delete": false
        }
        ```
        """
        logger.info(f"Creating new group permission '{permission_name}'")
        permission = Permissions.from_keys(default_if_key_not_present=False, **kwargs)
        return AuthApi().create_group_permission(State.state, permission_name=permission_name, permissions=permission)

    @api.post('/create')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def create_group(session_user: User, group_name: str, permissions: str) -> JsonResponse:
        """
        ### Create a new group

        Creates a new group with the specified name and associated permissions.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to create.
        - `permissions` (`str`): The name of the permission group to associate with this group.

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'editors', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/create
        {
            "group_name": "editors",
            "permissions": "edit_permissions"
        }
        ```
        """
        logger.info(f'Creating new group {group_name} with permissions {permissions}')
        return AuthApi().create_group(state=State.state, group_name=group_name, permission_group=permissions)

    @api.post('/join')
    @json_endpoint
    @require_session
    async def join_group(session_user: User, group_name: str) -> WebResponse:
        """
        ### Join a group

        Adds the authenticated user to the specified group. Requires an active session.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to join.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/join
        {
            "group_name": "editors"
        }
        ```
        """
        logger.info(f'User {session_user.id} is joining group {group_name}')
        return AuthApi().join_group(state=State.state, user=session_user, group_name=group_name)

    @api.post('/leave')
    @json_endpoint
    @require_session
    async def leave_group(session_user: User, group_name: str) -> WebResponse:
        """
        ### Leave a group

        Removes the authenticated user from the specified group. Requires an active session.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to leave.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/leave
        {
            "group_name": "editors"
        }
        ```
        """
        logger.info(f'User {session_user.id} is leaving group {group_name}')
        return AuthApi().leave_group(state=State.state, user=session_user, group_name=group_name)
