# ruff: noqa: F401

import logging
import secrets
import uuid

from quart import Blueprint, render_template_string, request

from bw.auth.api import AuthApi
from bw.auth.decorators import (
    require_local,
    require_session,
    require_user_role,
    verify_csrf_from_form,
    with_default_session,
    with_token,
)
from bw.auth.permissions import Permissions
from bw.auth.remarks import Remark
from bw.auth.roles import Roles
from bw.models.auth import User
from bw.response import ChunkedResponse, JsonResponse, WebResponse
from bw.state import State
from bw.web_utils import (
    chunk_text_response,
    form_endpoint,
    html_endpoint,
    json_endpoint,
    load_template_from_disk,
    unwrap_headers,
    url_endpoint,
)

logger = logging.getLogger('bw.auth')


def define_auth(api: Blueprint):
    @api.get('/login/discord')
    @url_endpoint
    @unwrap_headers(('Authorization', str))
    async def get_discord_access_code(authorization: str) -> JsonResponse:
        """
        ### Retrieve Discord OAuth access code

        Returns the access code associated with the state parameter from the OAuth flow.
        The access code is deleted after retrieval.

        *Docstring generated by AI.*

        **Args:**
        - `state` (`str`): The state parameter from the Discord OAuth flow (path parameter).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'access_code': 'discord_oauth_code'}`
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/auth/login/discord
        Authorization: Bearer discord_access_code_here
        ```
        """
        state = authorization[7:]
        logger.info('Retrieving access code (Discord)')
        return AuthApi().retrieve_access_code(state=State.state, code_state=state)

    @api.post('/login/discord')
    @url_endpoint
    @with_token
    async def login_discord(token) -> JsonResponse:
        """
        ### Log in with Discord access token

        Authenticates a Discord user using their access token and creates a new session.
        If the access token is expired or invalid, returns a 401 error with reauth URL.

        *Docstring generated by AI.*

        **Args:**
        - `token` (`str`): The Discord access token (automatically extracted from Authorization header by
        `@with_token`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'session_token': 'abc123...', 'expire_time': '2024-12-31T23:59:59'}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/auth/login/discord
        Authorization: Bearer discord_access_token_here
        ```
        """
        logger.info('Creating new session (Discord)')
        return await AuthApi().login_with_discord(state=State.state, token=token)

    @api.post('/login')
    @form_endpoint
    @verify_csrf_from_form
    async def login_bourbon(username: str, password: str, remember: str = 'off') -> WebResponse:
        """
        ### Log in with Bourbon Warfare account

        Authenticates a Bourbon user using their username and password, then create a new session.
        If the user doesnt exist, or a wrong password is given, returns 401.

        **Args:**
        - `username` (`str`): the username of the user.
        - `password` (`str`): the password of the user.
        - `remember` (`bool`): if we should store this session as a cookie.

        **Returns:**
        - `WebResponse`:
          - **Success (302)**: if the user has successfully logged in
          - **Error (40*)**: HTTP 40* response with error message

        **Example:**
        ```
        POST /api/v1/auth/login
        username: tcvm
        password: hunter2
        remember: False
        ```
        """
        logger.info('Creating new session (Bourbon)')
        response = AuthApi().login_with_bourbon(state=State.state, username=username, password=password, redirect='/')
        if response.status_code >= 400:
            return WebResponse(status=401, response='Password does not match login')

        session_token = response.state['session_token']
        AuthApi().store_session_cookie(session_token, permanent=remember == 'on')

        return response

    @api.post('/login/bot')
    @json_endpoint
    async def login_bot(bot_token: str) -> JsonResponse:
        """
        ### Log in with bot token

        Authenticates a bot user and creates a new API session.

        *Docstring generated by AI.*

        **Args:**
        - `bot_token` (`str`): The bot token for authentication.

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'session_token': 'abc123...', 'expire_time': '2024-12-31T23:59:59'}`
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/auth/login/bot
        {
            "bot_token": "your_bot_token_here"
        }
        ```
        """
        logger.info('Creating new session (bot)')
        return AuthApi().login_with_bot(state=State.state, bot_token=bot_token)
