# ruff: noqa: F401

import logging
import secrets
import uuid

from quart import Blueprint, render_template_string, request

from bw.auth.api import AuthApi
from bw.auth.decorators import (
    require_local,
    require_session,
    require_user_role,
    verify_csrf_from_form,
    with_default_session,
    with_token,
)
from bw.auth.permissions import Permissions
from bw.auth.remarks import Remark
from bw.auth.roles import Roles
from bw.models.auth import User
from bw.response import ChunkedResponse, JsonResponse, WebResponse
from bw.state import State
from bw.web_utils import (
    chunk_text_response,
    form_endpoint,
    html_endpoint,
    json_endpoint,
    load_template_from_disk,
    unwrap_headers,
    url_endpoint,
)

logger = logging.getLogger('bw.auth')


def define_group(api: Blueprint):
    permission_blueprint = Blueprint('permission', __name__, url_prefix='/permission')

    @api.post('/create/permission')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def create_group_permission(session_user: User, permission_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new group permission

        Creates a new group permission with the specified name and permission settings.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `permission_name` (`str`): The name of the permission to create.
        - `**kwargs`: Permission settings as key-value pairs (e.g., `can_read=True`, `can_write=False`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'read_access', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/create/permission
        {
            "permission_name": "read_access",
            "can_read": true,
            "can_write": false,
            "can_delete": false
        }
        ```
        """
        logger.info(f"Creating new group permission '{permission_name}'")
        permission = Permissions.from_keys(default_if_key_not_present=False, **kwargs)
        return AuthApi().create_group_permission(State.state, permission_name=permission_name, permissions=permission)

    @api.post('/create')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def create_group(session_user: User, group_name: str, permissions: str) -> JsonResponse:
        """
        ### Create a new group

        Creates a new group with the specified name and associated permissions.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to create.
        - `permissions` (`str`): The name of the permission group to associate with this group.

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'editors', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/create
        {
            "group_name": "editors",
            "permissions": "edit_permissions"
        }
        ```
        """
        logger.info(f'Creating new group {group_name} with permissions {permissions}')
        return AuthApi().create_group(state=State.state, group_name=group_name, permission_group=permissions)

    @api.post('/join')
    @json_endpoint
    @require_session
    async def join_group(session_user: User, group_name: str) -> WebResponse:
        """
        ### Join a group

        Adds the authenticated user to the specified group. Requires an active session.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to join.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (404)**: HTTP 404 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/join
        {
            "group_name": "editors"
        }
        ```
        """
        logger.info(f'User {session_user.id} is joining group {group_name}')
        return AuthApi().join_group(state=State.state, user=session_user, group_name=group_name)

    @api.post('/leave')
    @json_endpoint
    @require_session
    async def leave_group(session_user: User, group_name: str) -> WebResponse:
        """
        ### Leave a group

        Removes the authenticated user from the specified group. Requires an active session.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to leave.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/group/leave
        {
            "group_name": "editors"
        }
        ```
        """
        logger.info(f'User {session_user.id} is leaving group {group_name}')
        return AuthApi().leave_group(state=State.state, user=session_user, group_name=group_name)

    @api.get('/list')
    @url_endpoint
    @require_session
    async def list_groups(session_user: User) -> JsonResponse:
        """
        ### List all groups

        Retrieves all groups in the system with their associated permissions.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'groups': [
          {'id': 1, 'name': 'editors', 'permissions': 2},
          {'id': 2, 'name': 'viewers', 'permissions': 1}
          ]
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/group/list
        ```
        """
        return AuthApi().get_all_groups(State.state)

    @api.delete('/<string:group_name>')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def delete_group(session_user: User, group_name: str) -> WebResponse:
        """
        ### Delete a group

        Deletes the specified group and all user associations.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `group_name` (`str`): The name of the group to delete (path parameter).

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        DELETE /api/v1/group/editors
        ```
        """
        logger.info(f'Deleting group {group_name}')
        return AuthApi().delete_group(State.state, group_name=group_name)

    @permission_blueprint.get('/list')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def list_permissions(session_user: User) -> JsonResponse:
        """
        ### List all group permissions

        Retrieves all group permissions in the system.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'permissions': [
          {'name': 'read_access', 'can_upload_mission': False, ...},
          {'name': 'write_access', 'can_upload_mission': True, ...}
          ]
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/group/permission/list
        ```
        """
        return AuthApi().get_all_permissions(State.state)

    @permission_blueprint.put('/<string:permission_name>')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def edit_permission(session_user: User, permission_name: str, **kwargs) -> JsonResponse:
        """
        ### Edit a group permission

        Updates the permission settings for an existing group permission.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `permission_name` (`str`): The name of the permission to edit (path parameter).
        - `**kwargs`: Permission settings as key-value pairs (e.g., `can_upload_mission=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'name': 'read_access'}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        PUT /api/v1/group/permission/read_access
        {
            "can_upload_mission": true,
            "can_test_mission": false
        }
        ```
        """
        logger.info(f'Editing permission {permission_name}')
        permission = Permissions.from_keys(default_if_key_not_present=False, **kwargs)
        return AuthApi().edit_permission(State.state, permission_name=permission_name, permissions=permission)

    @permission_blueprint.delete('/<string:permission_name>')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_group)
    async def delete_permission(session_user: User, permission_name: str) -> WebResponse:
        """
        ### Delete a group permission

        Deletes the specified group permission.
        Requires an active session and the `can_create_group` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `permission_name` (`str`): The name of the permission to delete (path parameter).

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        DELETE /api/v1/group/permission/read_access
        ```
        """
        logger.info(f'Deleting permission {permission_name}')
        return AuthApi().delete_permission(State.state, permission_name=permission_name)

    api.register_blueprint(permission_blueprint)
