# ruff: noqa: F401

import logging
import secrets
import uuid

from quart import Blueprint, render_template_string, request

from bw.auth.api import AuthApi
from bw.auth.decorators import (
    require_local,
    require_session,
    require_user_role,
    verify_csrf_from_form,
    with_default_session,
    with_token,
)
from bw.auth.permissions import Permissions
from bw.auth.remarks import Remark
from bw.auth.roles import Roles
from bw.models.auth import User
from bw.response import ChunkedResponse, JsonResponse, WebResponse
from bw.state import State
from bw.web_utils import (
    chunk_text_response,
    form_endpoint,
    html_endpoint,
    json_endpoint,
    load_template_from_disk,
    unwrap_headers,
    url_endpoint,
)

logger = logging.getLogger('bw.auth')


def define_html(frontend: Blueprint, parts: Blueprint):
    @frontend.get('/login')
    @html_endpoint(template_path='auth/login.html', title='Sign in to Bourbon Warfare')
    @with_default_session
    async def login_page(session_token: str, html: str) -> str:
        csrf_token = AuthApi().set_csrf_token(State.state, session_token).state
        AuthApi().store_session_cookie(session_token)
        return await render_template_string(html, csrf_token=csrf_token)

    @frontend.get('/verify')
    @html_endpoint(template_path='auth/verify.html', title='Verified your Bourbon Warfare account')
    async def verify_page(html: str) -> str:
        token = request.args.get('token')
        if token:
            response = AuthApi().verify_email(State.state, token)
            verified = response.status_code == 200
        else:
            verified = False
        return await render_template_string(html, verified=verified)

    @frontend.get('/register')
    @html_endpoint(template_path='auth/create_account.html', title='Register a Bourbon Warfare account')
    @with_default_session
    async def register_page(session_token: str, html: str) -> str:
        csrf_token = AuthApi().set_csrf_token(State.state, session_token).state
        AuthApi().store_session_cookie(session_token)
        return await render_template_string(html, csrf_token=csrf_token)

    @frontend.get('/recover')
    @html_endpoint(template_path='auth/recover.html', title='Recover your Bourbon Warfare account')
    @with_default_session
    async def recover_page(session_token: str, html: str) -> str:
        csrf_token = AuthApi().set_csrf_token(State.state, session_token).state
        AuthApi().store_session_cookie(session_token)
        token = request.args.get('token')
        if token:
            html = await load_template_from_disk(template_path='auth/reset_password.html')
            return await render_template_string(html, csrf_token=csrf_token, token=token)
        return await render_template_string(html, csrf_token=csrf_token)

    @frontend.get('/login/discord')
    @html_endpoint(template_path='auth/oauth/discord.html', title='Logged in with Discord')
    async def login_discord_redirect(html: str) -> str:
        """
        ### Discord OAuth2 redirect endpoint

        Receives the OAuth2 redirect from Discord and stores the access code in the database.
        The client will then request the access code using the state parameter to complete
        authentication.

        *Docstring generated by AI.*

        **Args:**
        - `html` (`str`): The HTML template content (automatically injected by `@html_endpoint`).
        - `code` (`str`): The access code from Discord OAuth (query parameter).
        - `state` (`str`): The state parameter from Discord OAuth (query parameter).

        **Returns:**
        - `HtmlResponse`: HTML response with content-type 'text/html'
          - **Success (200)**: Rendered HTML page indicating successful authentication

        **Example:**
        ```
        GET /login/discord?code=discord_oauth_code&state=random_state_token
        ```
        """
        code = request.args.get('code', default='', type=str)
        state = request.args.get('state', default=secrets.token_urlsafe(32), type=str)
        logger.info('OAuth redirect (Discord)')
        try:
            AuthApi().register_access_code(state=State.state, code=code, code_state=state)
        finally:
            return html  # noqa: B012

    @frontend.get('/remarks')
    @html_endpoint(template_path='squad.xml', title='Bourbon Warfare Squad XML', return_partial=True, mimetype='text/xml')
    async def squad_xml(html: str) -> str:
        response = AuthApi().all_remarks(State.state)
        remarks = [Remark(**remark) for remark in await response.as_json_list()]
        final = await render_template_string(html, remarks=remarks)
        return final
