# ruff: noqa: F401

import logging
import secrets
import uuid

from quart import Blueprint, render_template_string, request

from bw.auth.api import AuthApi
from bw.auth.decorators import (
    require_local,
    require_session,
    require_user_role,
    verify_csrf_from_form,
    with_default_session,
    with_token,
)
from bw.auth.permissions import Permissions
from bw.auth.remarks import Remark
from bw.auth.roles import Roles
from bw.models.auth import User
from bw.response import ChunkedResponse, JsonResponse, WebResponse
from bw.state import State
from bw.web_utils import (
    chunk_text_response,
    form_endpoint,
    html_endpoint,
    json_endpoint,
    load_template_from_disk,
    unwrap_headers,
    url_endpoint,
)

logger = logging.getLogger('bw.auth')


def define_user(api: Blueprint, local: Blueprint):
    local_role_blueprint = Blueprint('local_role', __name__, url_prefix='/role')
    role_blueprint = Blueprint('role', __name__, url_prefix='/role')

    remark_blueprint = Blueprint('remark', __name__, url_prefix='/remark')

    @api.get('/')
    @url_endpoint
    @require_session
    async def get_user_info(session_user: User) -> JsonResponse:
        """
        ### Get authenticated user information

        Retrieves public information about the authenticated user, including UUID, creation date,
        and group memberships.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'uuid': '12345678-1234-5678-9012-123456789012',
          'creation_date': '2023-01-01T00:00:00',
          'groups': ['group1', 'group2']
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/user/
        ```
        """
        return AuthApi().user_info(state=State.state, user=session_user)

    @api.post('/recover')
    @form_endpoint
    @verify_csrf_from_form
    @require_session(require_user=False, require_authenticated=False)
    async def recover(email: str) -> WebResponse:
        response = AuthApi().send_recovery_email(State.state, email)
        if response.status_code >= 400:
            return response

        html = await load_template_from_disk(template_path='auth/recover_sent.html')
        return chunk_text_response(
            html, mimetype='text/html', headers={'HX-Reswap': 'outerHTML', 'HX-Retarget': '#auth-card', **response.headers}
        )

    @api.post('/recover/reset')
    @form_endpoint
    @verify_csrf_from_form
    @require_session(require_user=False, require_authenticated=False)
    async def recover_reset(token: str, password: str) -> WebResponse:
        response = AuthApi().recover_bourbon_account(State.state, token, password)
        if response.status_code >= 400:
            return response

        html = await load_template_from_disk(template_path='auth/recover_success.html')
        return chunk_text_response(
            html, mimetype='text/html', headers={'HX-Reswap': 'outerHTML', 'HX-Retarget': '#auth-card', **response.headers}
        )

    @api.post('/verify/resend')
    @form_endpoint
    @verify_csrf_from_form
    @require_session(require_user=False, require_authenticated=False)
    async def resend_verification(email: str) -> WebResponse:
        response = AuthApi().resend_verification_email(State.state, email)
        if response.status_code >= 400:
            return response

        html = await load_template_from_disk(template_path='auth/verification_resent.html')
        return chunk_text_response(
            html, mimetype='text/html', headers={'HX-Reswap': 'outerHTML', 'HX-Retarget': '#auth-card', **response.headers}
        )

    @api.post('/register')
    @verify_csrf_from_form
    @form_endpoint
    @require_session(require_user=False, require_authenticated=False)
    async def register(csrf_token: str, username: str, email: str, password: str) -> WebResponse:
        response = AuthApi().create_new_user_bourbon(State.state, username, email, password)
        if response.status_code >= 400:
            return response

        html = await load_template_from_disk(template_path='auth/registration_success.html')
        final_html = await render_template_string(html, username=username, email=email, csrf_token=csrf_token)
        return chunk_text_response(
            final_html, mimetype='text/html', headers={'HX-Reswap': 'outerHTML', 'HX-Retarget': '#auth-card', **response.headers}
        )

    @api.get('/list')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def list_users(session_user: User) -> JsonResponse:
        """
        ### List all users with pagination

        Retrieves a paginated list of all users with their roles, groups, and connected apps.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `page` (`int`): The page number to retrieve (query parameter, default: 1).
        - `page_size` (`int`): Number of users per page (query parameter, default: 50).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'users': [...],
          'total': 150,
          'page': 1,
          'page_size': 50,
          'total_pages': 3
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/user/list?page=1&page_size=50
        ```
        """
        page = request.args.get('page', default=1, type=int)
        page_size = request.args.get('page_size', default=50, type=int)
        return AuthApi().list_all_users(State.state, page=page, page_size=page_size)

    @role_blueprint.post('/create')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def create_role(session_user: User, role_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new role

        Creates a new role with the specified name and role permissions.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to create.
        - `**kwargs`: Role permissions as key-value pairs (e.g., `can_create_group=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'admin', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/user/role/create
        {
            "role_name": "admin",
            "can_create_group": true,
            "can_manage_server": true
        }
        ```
        """
        logger.info(f"Creating new role '{role_name}'")
        role = Roles.from_keys(**kwargs)
        return AuthApi().create_role(State.state, role_name=role_name, roles=role)

    @role_blueprint.post('/assign')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def assign_role(session_user: User, role_name: str, user_uuid: str) -> WebResponse:
        """
        ### Assign a role to a user

        Assigns the specified role to the user with the given UUID.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to assign.
        - `user_uuid` (`str`): The UUID of the user to assign the role to.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/v1/user/role/assign
        {
            "role_name": "admin",
            "user_uuid": "12345678-1234-5678-9012-123456789012"
        }
        ```
        """
        logger.info(f'Assigning {role_name} to user {user_uuid}')
        return AuthApi().assign_role(State.state, role_name=role_name, user_uuid=uuid.UUID(hex=user_uuid))

    @role_blueprint.get('/list')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def list_roles(session_user: User) -> JsonResponse:
        """
        ### List all roles

        Retrieves all roles in the system with their permission settings.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{
          'roles': [
          {'name': 'admin', 'can_create_role': True, ...},
          {'name': 'user', 'can_create_role': False, ...}
          ]
          }`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        GET /api/v1/user/role/list
        ```
        """
        return AuthApi().get_all_roles(State.state)

    @role_blueprint.put('/<string:role_name>')
    @json_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def edit_role(session_user: User, role_name: str, **kwargs) -> JsonResponse:
        """
        ### Edit a role

        Updates the permissions for an existing role.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to edit (path parameter).
        - `**kwargs`: Role permissions as key-value pairs (e.g., `can_create_group=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (200)**: `{'name': 'admin'}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        PUT /api/v1/user/role/admin
        {
            "can_create_group": true,
            "can_manage_server": false
        }
        ```
        """
        logger.info(f'Editing role {role_name}')
        role = Roles.from_keys(**kwargs)
        return AuthApi().edit_role(State.state, role_name=role_name, roles=role)

    @role_blueprint.delete('/<string:role_name>')
    @url_endpoint
    @require_session
    @require_user_role(Roles.can_create_role)
    async def delete_role(session_user: User, role_name: str) -> WebResponse:
        """
        ### Delete a role

        Deletes the specified role and removes it from all users.
        Requires an active session and the `can_create_role` role.

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to delete (path parameter).

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        DELETE /api/v1/user/role/admin
        ```
        """
        logger.info(f'Deleting role {role_name}')
        return AuthApi().delete_role(State.state, role_name=role_name)

    @local_role_blueprint.post('/create')
    @json_endpoint
    @require_local
    @require_session
    async def local_create_role(session_user: User, role_name: str, **kwargs) -> JsonResponse:
        """
        ### Create a new role (Local only)

        Creates a new role with the specified name and role permissions.
        This endpoint is only available for local requests (internal server administration).

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to create.
        - `**kwargs`: Role permissions as key-value pairs (e.g., `can_create_group=True`).

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'name': 'admin', 'status': 201}`
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (409)**: HTTP 409 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/role/create
        {
            "role_name": "admin",
            "can_create_group": true,
            "can_manage_users": true
        }
        ```
        """
        logger.info('Creating new role (Local)')
        role = Roles.from_keys(**kwargs)
        return AuthApi().create_role(State.state, role_name=role_name, roles=role)

    # required to bootstrap server
    @local.post('/create/bot')
    @url_endpoint
    @require_local
    async def local_create_bot() -> JsonResponse:
        """
        ### Create a new bot user (Local only)

        Creates a new user and links a bot user to it, returning the bot token.
        This endpoint is only available for local requests (internal server bootstrapping).

        *Docstring generated by AI.*

        **Returns:**
        - `JsonResponse`:
          - **Success (201)**: `{'bot_token': 'abc123...', 'status': 201}`
          - **Error (400)**: HTTP 400 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/create/bot
        ```
        """
        logger.info('Creating new bot user (Local)')
        return AuthApi().create_new_user_bot(state=State.state)

    @local_role_blueprint.post('/assign')
    @json_endpoint
    @require_local
    @require_session
    async def local_assign_role(session_user: User, role_name: str, user_uuid: str) -> WebResponse:
        """
        ### Assign a role to a user (Local only)

        Assigns the specified role to the user with the given UUID.
        This endpoint is only available for local requests (internal server administration).

        *Docstring generated by AI.*

        **Args:**
        - `session_user` (`User`): The authenticated user (automatically injected by `@require_session`).
        - `role_name` (`str`): The name of the role to assign.
        - `user_uuid` (`str`): The UUID of the user to assign the role to.

        **Returns:**
        - `WebResponse`:
          - **Success (200)**: Empty response body
          - **Error (401)**: HTTP 401 response with error message (not JSON)
          - **Error (403)**: HTTP 403 response with error message (not JSON)
          - **Error (404)**: HTTP 404 response with error message (not JSON)

        **Example:**
        ```
        POST /api/local/user/role/assign
        {
            "role_name": "admin",
            "user_uuid": "12345678-1234-5678-9012-123456789012"
        }
        ```
        """
        logger.info(f'Assigning {role_name} to user {user_uuid} (Local)')
        return AuthApi().assign_role(State.state, role_name=role_name, user_uuid=uuid.UUID(hex=user_uuid))

    @remark_blueprint.post('/')
    @form_endpoint
    @require_session
    async def update_remark(
        session_user: User, profile_name: str, steam_id: str, nickname: str | None, remark: str | None
    ) -> WebResponse:
        return AuthApi().update_remark(
            State.state, session_user, Remark(profile_name=profile_name, nickname=nickname, steam_id=steam_id, remark=remark)
        )

    @remark_blueprint.get('/')
    @url_endpoint
    @require_session
    async def get_remark(session_user: User) -> JsonResponse:
        return AuthApi().get_remark(State.state, session_user)

    @remark_blueprint.get('/all')
    @url_endpoint
    @require_session
    async def all_remarks() -> ChunkedResponse:
        return AuthApi().all_remarks(State.state)

    api.register_blueprint(remark_blueprint)
    api.register_blueprint(role_blueprint)
    local.register_blueprint(local_role_blueprint)
