"""add realtime event role

Revision ID: 1032930c59e4
Revises: 8cefd930c03d
Create Date: 2026-03-06 17:57:06.888129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1032930c59e4'
down_revision: Union[str, Sequence[str], None] = '8cefd930c03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('can_publish_realtime_events', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'can_publish_realtime_events')
    # ### end Alembic commands ###
