"""process manager

Revision ID: 1323f110de9a
Revises: 57f3d1fbce96
Create Date: 2026-07-16 05:11:10.171184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1323f110de9a'
down_revision: Union[str, Sequence[str], None] = '57f3d1fbce96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('pid', sa.BigInteger(), nullable=True),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('status_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'STARTING', 'STOPPING', 'DELETING', 'DELETED', 'ERROR', name='state'), nullable=False),
    sa.Column('state_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['processes.id'], name='parent_process_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'name', name='namespace_needs_unique_name'),
    sa.UniqueConstraint('pid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    sa.Enum('IDLE', 'STARTING', 'STOPPING', 'DELETING', 'DELETED', 'ERROR', name='state').drop(op.get_bind())
    # ### end Alembic commands ###
