"""change tag from str to int

Revision ID: 252abe947a54
Revises: 3ee99df44112
Create Date: 2025-06-30 19:20:22.817152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252abe947a54'
down_revision: Union[str, Sequence[str], None] = '3ee99df44112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_types', sa.Column('numeric_tag', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('mission_types_tag_map_key'), 'mission_types', type_='unique')
    op.create_unique_constraint(None, 'mission_types', ['numeric_tag'])
    op.drop_column('mission_types', 'tag_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_types', sa.Column('tag_map', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mission_types', type_='unique')
    op.create_unique_constraint(op.f('mission_types_tag_map_key'), 'mission_types', ['tag_map'], postgresql_nulls_not_distinct=False)
    op.drop_column('mission_types', 'numeric_tag')
    # ### end Alembic commands ###
