"""unique missions

Revision ID: 3ee99df44112
Revises: 9b5126a0859f
Create Date: 2025-06-27 23:17:59.682773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee99df44112'
down_revision: Union[str, Sequence[str], None] = '9b5126a0859f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.add_column('missions', sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.create_unique_constraint(None, 'missions', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='unique')
    op.drop_column('missions', 'creation_date')
    op.drop_column('missions', 'uuid')
    # ### end Alembic commands ###
