"""add state parameter to session to avoid sending state back to the frontend

Revision ID: 45fb4e555ab0
Revises: b6f0e3d8c7a1
Create Date: 2026-09-24 20:55:20.173902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fb4e555ab0'
down_revision: Union[str, Sequence[str], None] = 'b6f0e3d8c7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arma_server'), table_name='arma_events')
    op.create_index(op.f('ix_arma_events_server'), 'arma_events', ['server'], unique=False)
    op.add_column('sessions', sa.Column('state', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'state')
    op.drop_index(op.f('ix_arma_events_server'), table_name='arma_events')
    op.create_index(op.f('ix_arma_server'), 'arma_events', ['server'], unique=False)
    # ### end Alembic commands ###
