"""workshop-mod-update-date

Revision ID: 4bdd7db7171b
Revises: 638813e60701
Create Date: 2026-02-17 19:28:12.439085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdd7db7171b'
down_revision: Union[str, Sequence[str], None] = '638813e60701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mods', sa.Column('name', sa.String(), nullable=False))
    op.add_column('mods', sa.Column('server_update_date', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_mods_name'), 'mods', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mods_name'), table_name='mods')
    op.drop_column('mods', 'server_update_date')
    op.drop_column('mods', 'name')
    # ### end Alembic commands ###
