"""update constraints

Revision ID: 53bf853812a0
Revises: e259b8c80c6f
Create Date: 2025-06-24 14:56:37.175084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bf853812a0'
down_revision: Union[str, Sequence[str], None] = 'e259b8c80c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'discord_users', ['discord_id'])
    op.create_unique_constraint(None, 'discord_users', ['user_id'])
    op.create_unique_constraint(None, 'group_permissions', ['name'])
    op.create_unique_constraint(None, 'groups', ['name'])
    op.add_column('mission_iterations', sa.Column('mission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mission_iterations', 'missions', ['mission_id'], ['id'])
    op.create_unique_constraint(None, 'mission_types', ['name'])
    op.create_unique_constraint(None, 'passed_missions', ['iteration_id'])
    op.alter_column('sessions', 'token',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_unique_constraint(None, 'sessions', ['user_id'])
    op.create_unique_constraint(None, 'user_roles', ['name'])
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'sessions', type_='unique')
    op.alter_column('sessions', 'token',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_constraint(None, 'passed_missions', type_='unique')
    op.drop_constraint(None, 'mission_types', type_='unique')
    op.drop_constraint(None, 'mission_iterations', type_='foreignkey')
    op.drop_column('mission_iterations', 'mission_id')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'group_permissions', type_='unique')
    op.drop_constraint(None, 'discord_users', type_='unique')
    op.drop_constraint(None, 'discord_users', type_='unique')
    # ### end Alembic commands ###
