"""initial

Revision ID: 57f3d1fbce96
Revises: 
Create Date: 2026-07-09 03:25:35.990978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f3d1fbce96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arma_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('discord_oauth_codes',
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expire_time', sa.DateTime(), server_default=sa.text('LOCALTIMESTAMP + make_interval(secs=>3600.0)'), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_creation_date'), 'events', ['creation_date'], unique=False)
    op.create_table('group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('can_upload_mission', sa.Boolean(), nullable=False),
    sa.Column('can_test_mission', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mission_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('signoffs_required', sa.Integer(), nullable=False),
    sa.Column('numeric_tag', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('numeric_tag')
    )
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.String(), nullable=False),
    sa.Column('last_update_date', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mods_name'), 'mods', ['name'], unique=False)
    op.create_index(op.f('ix_mods_workshop_id'), 'mods', ['workshop_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('can_create_role', sa.Boolean(), nullable=False),
    sa.Column('can_create_group', sa.Boolean(), nullable=False),
    sa.Column('can_manage_server', sa.Boolean(), nullable=False),
    sa.Column('can_publish_realtime_events', sa.Boolean(), nullable=False),
    sa.Column('can_manage_session', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permissions'], ['group_permissions.id'], name='linked_group_permission_for_group'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('published_events',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('published_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['events.id'], name='linked_event_for_published'),
    sa.PrimaryKeyConstraint('event')
    )
    op.create_index(op.f('ix_published_events_published_time'), 'published_events', ['published_time'], unique=False)
    op.create_table('queued_events',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('queued_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['events.id'], name='linked_event_for_queued'),
    sa.PrimaryKeyConstraint('event')
    )
    op.create_index(op.f('ix_queued_events_queued_time'), 'queued_events', ['queued_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['user_roles.id'], name='linked_role_for_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='linked_user_for_bot'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('discord_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='linked_user_for_discord'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('server', sa.String(length=256), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('map', sa.String(length=256), nullable=False),
    sa.Column('mission_type', sa.Integer(), nullable=False),
    sa.Column('special_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name='user_who_uploaded_mission'),
    sa.ForeignKeyConstraint(['mission_type'], ['mission_types.id'], name='associated_mission_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid', 'server', name='mission_upload_only_once_to_server')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'PASSED', name='teststatus'), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['users.id'], name='user_who_posted_review'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('expire_time', sa.DateTime(), server_default=sa.text('LOCALTIMESTAMP + make_interval(secs=>3600.0)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='linked_user_for_session'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='linked_group_for_group'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='linked_user_for_group'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='can_be_added_to_group_once')
    )
    op.create_table('mission_iterations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('min_player_count', sa.Integer(), nullable=False),
    sa.Column('max_player_count', sa.Integer(), nullable=False),
    sa.Column('desired_player_count', sa.Integer(), nullable=False),
    sa.Column('safe_start_length', sa.Integer(), nullable=False),
    sa.Column('mission_length', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('bwmf_version', sa.String(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iteration', 'mission_id', name='mission_has_single_iteration'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('passed_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('date_passed', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['mission_iterations.id'], name='iteration_passed'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name='mission_passed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iteration_id')
    )
    op.create_table('played_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('play_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('orbat', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['mission_iterations.id'], name='iteration_played_in_session'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name='mission_played_in_session'),
    sa.ForeignKeyConstraint(['session_id'], ['arma_sessions.id'], name='session_mission_played_in'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('date_tested', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['mission_iterations.id'], name='tested_iteration'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='attached_review'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id'),
    sa.UniqueConstraint('review_id', 'iteration_id', name='review_maps_to_single_iteration'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('test_cosigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], name='result_cosigned'),
    sa.ForeignKeyConstraint(['tester_id'], ['users.id'], name='user_who_cosigned'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_result_id', 'tester_id', name='can_only_cosign_once')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cosigns')
    op.drop_table('test_results')
    op.drop_table('played_missions')
    op.drop_table('passed_missions')
    op.drop_table('mission_iterations')
    op.drop_table('user_groups')
    op.drop_table('sessions')
    op.drop_table('reviews')
    sa.Enum('FAILED', 'PASSED', name='teststatus').drop(op.get_bind())
    op.drop_table('missions')
    op.drop_table('discord_users')
    op.drop_table('bot_users')
    op.drop_table('users')
    op.drop_index(op.f('ix_queued_events_queued_time'), table_name='queued_events')
    op.drop_table('queued_events')
    op.drop_index(op.f('ix_published_events_published_time'), table_name='published_events')
    op.drop_table('published_events')
    op.drop_table('groups')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_mods_workshop_id'), table_name='mods')
    op.drop_index(op.f('ix_mods_name'), table_name='mods')
    op.drop_table('mods')
    op.drop_table('mission_types')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_events_creation_date'), table_name='events')
    op.drop_table('events')
    op.drop_table('discord_oauth_codes')
    op.drop_table('arma_sessions')
    # ### end Alembic commands ###
