"""add session model

Revision ID: 5e3d0cb7384c
Revises: b3c8e7ed8933
Create Date: 2026-06-08 19:17:23.171229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3d0cb7384c'
down_revision: Union[str, Sequence[str], None] = 'b3c8e7ed8933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arma_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('played_missions', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'played_missions', 'arma_sessions', ['session_id'], ['id'])
    op.add_column('user_roles', sa.Column('can_manage_session', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'can_manage_session')
    op.drop_constraint(None, 'played_missions', type_='foreignkey')
    op.drop_column('played_missions', 'session_id')
    op.drop_table('arma_sessions')
    # ### end Alembic commands ###
