"""add a mission tag into the type

Revision ID: 63ac4f0e2c71
Revises: 898df57974e6
Create Date: 2025-06-27 14:48:42.802776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ac4f0e2c71'
down_revision: Union[str, Sequence[str], None] = '898df57974e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_types', sa.Column('tag_map', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'mission_types', ['tag_map'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mission_types', type_='unique')
    op.drop_column('mission_types', 'tag_map')
    # ### end Alembic commands ###
