"""uuid-unique-to-server

Revision ID: 7498f41deef6
Revises: 87ef671e82fd
Create Date: 2026-08-07 14:44:34.123693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7498f41deef6'
down_revision: Union[str, Sequence[str], None] = '87ef671e82fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('missions_uuid_key'), 'missions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('missions_uuid_key'), 'missions', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
