"""add more info to iterations

Revision ID: 7e1ad0ac84e1
Revises: f2bc9683e886
Create Date: 2025-06-30 20:24:04.958836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1ad0ac84e1'
down_revision: Union[str, Sequence[str], None] = 'f2bc9683e886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_iterations', sa.Column('mission_length', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission_iterations', 'mission_length')
    # ### end Alembic commands ###
