"""remove duplicate field

Revision ID: 82b00afe17f6
Revises: be227ceaed5a
Create Date: 2026-02-17 19:37:01.130885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b00afe17f6'
down_revision: Union[str, Sequence[str], None] = 'be227ceaed5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mods', 'server_update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mods', sa.Column('server_update_date', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
