"""bourbon user verification

Revision ID: 87ef671e82fd
Revises: a2566870981c
Create Date: 2026-08-04 18:45:09.726071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ef671e82fd'
down_revision: Union[str, Sequence[str], None] = 'a2566870981c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bourbon_user_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('expire_time', sa.DateTime(), server_default=sa.text('LOCALTIMESTAMP + make_interval(secs=>600.0)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bourbon_user_codes')
    # ### end Alembic commands ###
