"""add flag field for mission

Revision ID: 898df57974e6
Revises: 91c5f463160f
Create Date: 2025-06-27 14:10:29.485462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898df57974e6'
down_revision: Union[str, Sequence[str], None] = '91c5f463160f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('special_flags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'special_flags')
    # ### end Alembic commands ###
