"""new default pt2

Revision ID: 8cefd930c03d
Revises: 3cf9639aaf57
Create Date: 2026-02-27 23:26:48.829408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cefd930c03d'
down_revision: Union[str, Sequence[str], None] = '3cf9639aaf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'creation_date',
        existing_server_default=sa.text('CURRENT_DATE'),
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('played_missions', 'play_date',
        existing_server_default=sa.text('CURRENT_DATE'),
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('passed_missions', 'date_passed',
        existing_server_default=sa.text('CURRENT_DATE'),
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('mission_iterations', 'upload_date',
        existing_server_default=sa.text('CURRENT_DATE'),
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column('test_results', 'date_tested',
        existing_server_default=sa.text('CURRENT_DATE'),
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'creation_date',
        existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        server_default=sa.text('CURRENT_DATE')
    )
    op.alter_column('played_missions', 'play_date',
        existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        server_default=sa.text('CURRENT_DATE')
    )
    op.alter_column('passed_missions', 'date_passed',
        existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        server_default=sa.text('CURRENT_DATE')
    )
    op.alter_column('mission_iterations', 'upload_date',
        existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        server_default=sa.text('CURRENT_DATE')
    )
    op.alter_column('test_results', 'date_tested',
        existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        server_default=sa.text('CURRENT_DATE')
    )
    # ### end Alembic commands ###
