"""only allow one review mapped to one result

Revision ID: 9b5126a0859f
Revises: c08b335b88fd
Create Date: 2025-06-27 16:04:20.947523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5126a0859f'
down_revision: Union[str, Sequence[str], None] = 'c08b335b88fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test_results', ['review_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_results', type_='unique')
    # ### end Alembic commands ###
