"""add task processor

Revision ID: a2566870981c
Revises: f98172627490
Create Date: 2026-08-03 16:36:53.994626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2566870981c'
down_revision: Union[str, Sequence[str], None] = 'f98172627490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('time_until_stale', sa.Interval(), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETE', 'FAILED', 'STALE', name='taskstate'), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    sa.Enum('QUEUED', 'PROCESSING', 'COMPLETE', 'FAILED', 'STALE', name='taskstate').drop(op.get_bind())
    # ### end Alembic commands ###
