"""add enddate

Revision ID: a9ffa8cda9ae
Revises: 5e3d0cb7384c
Create Date: 2026-06-30 18:04:11.754555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ffa8cda9ae'
down_revision: Union[str, Sequence[str], None] = '5e3d0cb7384c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arma_sessions', sa.Column('finish_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arma_sessions', 'finish_date')
    # ### end Alembic commands ###
