"""add mission map to db

Revision ID: b3c8e7ed8933
Revises: fb6080ddaf58
Create Date: 2026-06-08 18:20:55.781307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c8e7ed8933'
down_revision: Union[str, Sequence[str], None] = 'fb6080ddaf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('map', sa.String(length=256), nullable=False))
    op.alter_column('user_roles', 'can_publish_realtime_events',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'can_publish_realtime_events',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('missions', 'map')
    # ### end Alembic commands ###
