"""change to orbat instead of playercount

Revision ID: b60cb79991a9
Revises: a9ffa8cda9ae
Create Date: 2026-07-01 17:49:23.560709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60cb79991a9'
down_revision: Union[str, Sequence[str], None] = 'a9ffa8cda9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('played_missions', sa.Column('orbat', sa.JSON(), nullable=False))
    op.drop_column('played_missions', 'player_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('played_missions', sa.Column('player_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('played_missions', 'orbat')
    # ### end Alembic commands ###
