"""Remove unique constraint on sessions

Revision ID: bae068e62276
Revises: ccbbdae988a1
Create Date: 2026-01-23 22:30:39.383661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae068e62276'
down_revision: Union[str, Sequence[str], None] = 'ccbbdae988a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_user_id_key'), 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sessions_user_id_key'), 'sessions', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
