"""change mod date updates

Revision ID: be227ceaed5a
Revises: 4bdd7db7171b
Create Date: 2026-02-17 19:34:20.690719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be227ceaed5a'
down_revision: Union[str, Sequence[str], None] = '4bdd7db7171b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mods', 'last_update_date',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mods', 'last_update_date',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
