"""discord access code

Revision ID: c6dc6ff219c1
Revises: bae068e62276
Create Date: 2026-02-07 23:12:56.224822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dc6ff219c1'
down_revision: Union[str, Sequence[str], None] = 'bae068e62276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_oauth_codes',
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expire_time', sa.DateTime(), server_default=sa.text('LOCALTIMESTAMP + make_interval(secs=>3600.0)'), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_oauth_codes')
    # ### end Alembic commands ###
