"""make server management permission a role

Revision ID: ccbbdae988a1
Revises: 16267a9afc62
Create Date: 2025-08-29 20:10:06.900372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbbdae988a1'
down_revision: Union[str, Sequence[str], None] = '16267a9afc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_permissions', 'can_manage_server')
    op.add_column('user_roles', sa.Column('can_manage_server', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'can_manage_server')
    op.add_column('group_permissions', sa.Column('can_manage_server', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
