"""add more info to iterations

Revision ID: f2bc9683e886
Revises: 252abe947a54
Create Date: 2025-06-30 20:22:52.551678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bc9683e886'
down_revision: Union[str, Sequence[str], None] = '252abe947a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_iterations', sa.Column('safe_start_length', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission_iterations', 'safe_start_length')
    # ### end Alembic commands ###
