"""add constraints to mission

Revision ID: f95b982c18ba
Revises: 47f624c46679
Create Date: 2026-02-26 23:49:36.716559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95b982c18ba'
down_revision: Union[str, Sequence[str], None] = '47f624c46679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mission_upload_only_once_to_server', 'missions', ['uuid', 'server'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mission_upload_only_once_to_server', 'missions', type_='unique')
    # ### end Alembic commands ###
