"""remove unique constraint

Revision ID: fb6080ddaf58
Revises: 3c1fee33d1b9
Create Date: 2026-04-07 17:58:06.716813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6080ddaf58'
down_revision: Union[str, Sequence[str], None] = '3c1fee33d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_event_id_key'), 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('events_event_id_key'), 'events', ['event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
