import time

from bw.error import NoTasksAvailable
from bw.models.tasks import TaskState
from bw.state import State
from bw.tasks.tasks import TasksStore


class Runner:
    def __init__(self):
        """
        ### Initialize the task runner

        Creates a new Runner instance and sets the default polling delay interval.

        *Docstring generated by AI.*

        **Async:** No

        **Returns:**
        - `None`: This method does not return a value.

        **Example:**
        ```python
        runner = Runner()
        # <Runner object>
        ```
        """
        self.delay: float = 0.25

    def process_task(self) -> bool:
        """
        ### Process a single task

        Pops the next available task from the task store, executes it, and
        records either completion or failure in the store.

        *Docstring generated by AI.*

        **Async:** No

        **Returns:**
        - `bool`: `True` if a task was popped and processed, or `False` if no tasks were available.

        **Example:**
        ```python
        processed = runner.process_task()
        # True
        ```
        """
        try:
            task = TasksStore().pop_task_to_process(State.state)
        except NoTasksAvailable:
            return False

        try:
            result = task()
        except Exception as err:  # noqa: BLE001
            TasksStore().fail_task(State.state, task, err)
        else:
            TasksStore().finish_task(State.state, task, result)
        return True

    def reap_stale_tasks(self):
        """
        ### Reap stale tasks

        Retrieves all stale tasks from the store and updates their state in
        the database to marked as stale.

        *Docstring generated by AI.*

        **Async:** No

        **Returns:**
        - `None`: This method does not return a value.

        **Example:**
        ```python
        runner.reap_stale_tasks()
        # None
        ```
        """
        for task in TasksStore().get_stale_tasks(State.state):
            TasksStore().fail_task(State.state, task, 'task has become stale', task_state=TaskState.STALE)

    def run(self):
        """
        ### Run the main task loop

        Executes an infinite loop that continuously processes available tasks,
        reaps stale tasks, and sleeps for the configured delay.

        *Docstring generated by AI.*

        **Async:** No

        **Returns:**
        - `None`: This method runs indefinitely and does not return.

        **Example:**
        ```python
        runner.run()
        # Infinite execution loop
        ```
        """
        while True:
            start_time = time.time()
            self.process_task()
            self.reap_stale_tasks()
            run_time = time.time() - start_time
            if run_time < self.delay:
                time.sleep(self.delay - run_time)
