from typing import Any
from uuid import UUID

from sqlalchemy import func, or_, select, update
from sqlalchemy.exc import NoResultFound

from bw.converters import make_json_safe
from bw.error import NoTasksAvailable
from bw.models.tasks import Task, TaskState
from bw.state import State
from bw.tasks import Kind


class TasksStore:
    def enqueue_task(self, state: State, task: Kind) -> UUID:
        """
        ### Enqueue a task

        Converts a task instance into a JSON-safe dictionary and inserts a new task
        record into the database within a transaction.

        *Docstring generated by AI.*

        **Async:** No

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `task` (`Kind`): The task instance to be enqueued.

        **Returns:**
        - `UUID`: The unique identifier of the enqueued task record.

        **Example:**
        ```python
        task_id = TasksStore().enqueue_task(state, task)
        # UUID('12345678-1234-5678-1234-567812345678')
        ```
        """
        with state.Session.begin() as session:
            task_row = Task(arguments=make_json_safe(task.to_dict()), uuid=task.uuid, time_until_stale=task.time_until_stale())
            session.add(task_row)
            return task_row.uuid

    def pop_task_to_process(self, state: State) -> Kind:
        """
        ### Pop a task to process

        Fetches the oldest queued task from the database using row locking,
        updates its status to processing, and returns it.

        *Docstring generated by AI.*

        **Async:** No

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Raises:**
        - `NoTasksAvailable`: If no tasks with queued status are available in the database.

        **Returns:**
        - `Kind`: The reconstructed task instance populated with arguments and UUID.

        **Example:**
        ```python
        task = TasksStore().pop_task_to_process(state)
        # <Kind object>
        ```
        """
        with state.Session.begin() as session:
            cte = (
                select(Task)
                .where(Task.state == TaskState.QUEUED)
                .order_by(Task.create_date)
                .limit(1)
                .with_for_update(skip_locked=True)
                .cte()
            )
            query = (
                update(Task)
                .add_cte(cte)
                .where(Task.id == cte.c.id)
                .values(state=TaskState.PROCESSING, start_date=func.current_timestamp())
                .returning(Task.arguments, Task.uuid)
            )
            try:
                arguments, uuid = session.execute(query).tuples().one()
            except NoResultFound:
                raise NoTasksAvailable()
        return Kind.from_dict(arguments, uuid)

    def fail_task(self, state: State, task: Kind, reason: Exception | str, *, task_state: TaskState = TaskState.FAILED):
        """
        ### Fail a task

        Updates the database record for a task to mark it as failed or stale
        and records the failure reason string.

        *Docstring generated by AI.*

        **Async:** No

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `task` (`Kind`): The task instance that failed.
        - `reason` (`Exception | str`): The exception or message describing the failure.
        - `task_state` (`TaskState`): The status state to set, defaulting to `TaskState.FAILED`.

        **Returns:**
        - `None`: This method does not return a value.

        **Example:**
        ```python
        TasksStore().fail_task(state, task, "Runtime error")
        # None
        ```
        """
        with state.Session.begin() as session:
            query = update(Task).where(Task.uuid == task.uuid).values(state=task_state, result={'reason': str(reason)})
            session.execute(query)

    def finish_task(self, state: State, task: Kind, result: dict[str, Any] | None):
        """
        ### Finish a task

        Updates the database record for a task to mark it as complete
        and records its result payload.

        *Docstring generated by AI.*

        **Async:** No

        **Args:**
        - `state` (`State`): The application state containing the database connection.
        - `task` (`Kind`): The completed task instance.
        - `result` (`dict[str, Any] | None`): The result data produced by execution, or None.

        **Returns:**
        - `None`: This method does not return a value.

        **Example:**
        ```python
        TasksStore().finish_task(state, task, {"status": "ok"})
        # None
        ```
        """
        with state.Session.begin() as session:
            query = update(Task).where(Task.uuid == task.uuid).values(state=TaskState.COMPLETE, result=result)
            session.execute(query)

    def get_stale_tasks(self, state: State) -> list[Kind]:
        """
        ### Get stale tasks

        Queries the database for tasks in queued or processing states that
        have exceeded their configured stale timeout threshold.

        *Docstring generated by AI.*

        **Async:** No

        **Args:**
        - `state` (`State`): The application state containing the database connection.

        **Returns:**
        - `list[Kind]`: A list of stale task instances retrieved from the database.

        **Example:**
        ```python
        stale_tasks = TasksStore().get_stale_tasks(state)
        # [<Kind object>]
        ```
        """
        with state.Session.begin() as session:
            query = select(Task).where(
                or_(Task.state == TaskState.QUEUED, Task.state == TaskState.PROCESSING),
                func.current_timestamp() - Task.start_date >= Task.time_until_stale,
            )
            tasks = session.execute(query).scalars().all()
            return [Kind.from_dict(task.arguments, task.uuid) for task in tasks]
